/**
 * MDX content library.
 *
 * In production (Cloudflare Workers):
 *   Uses a pre-compiled JSON cache (src/data/content-cache.json) bundled by
 *   esbuild into handler.mjs.  This avoids runtime filesystem reads, which
 *   fail on Cloudflare Workers because process.cwd() returns '/' and MDX
 *   files are not present in the deployed worker bundle.
 *
 * In local development:
 *   Falls back to live filesystem reads (hot-reload friendly).
 *   The cache file is empty ({}) in a fresh checkout, so the fs path is used
 *   automatically without any extra setup.
 */

import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import readingTime from 'reading-time';
import type { Article, ArticleFrontmatter } from '@/types/article';

// ── Pre-compiled cache (read from disk at build time, NOT bundled into Worker) ─
// Generated by: npm run content-cache
// Import only the articles slice (pregnancy, blog, parenting) — excludes
// products/ data. Products are handled separately by src/lib/products.ts.
//
// Uses fs.readFileSync instead of require() so esbuild does NOT bundle the
// 3.2 MB JSON into handler.mjs. All pages using this cache are force-static —
// the Cloudflare Worker serves pre-rendered HTML and never calls these
// functions at runtime, so the Worker never needs the JSON file.

type CompiledCache = Record<string, Record<string, Article>>;

let _articlesCache: CompiledCache | null | undefined = undefined;
function getCompiledCache(): CompiledCache | null {
  if (_articlesCache === undefined) {
    try {
      const cachePath = path.join(process.cwd(), 'src/data/content-cache-articles.json');
      const data = JSON.parse(fs.readFileSync(cachePath, 'utf-8')) as CompiledCache;
      _articlesCache = Object.keys(data).length === 0 ? null : data;
    } catch {
      _articlesCache = null;
    }
  }
  return _articlesCache;
}

// ── Filesystem helpers (local dev fallback) ──────────────────────────────────
const contentDir = path.join(process.cwd(), 'content');

function getContentDir(subDir: string): string {
  return path.join(contentDir, subDir);
}

function getMdxFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isFile() && d.name.endsWith('.mdx'))
    .map((d) => d.name);
}

function readArticleFromFs(subDir: string, slug: string): Article | null {
  const dir = getContentDir(subDir);
  const filePath = path.join(dir, `${slug}.mdx`);
  if (!fs.existsSync(filePath)) return null;

  const raw = fs.readFileSync(filePath, 'utf-8');
  const { data, content } = matter(raw);
  const stats = readingTime(content);

  return {
    ...(data as ArticleFrontmatter),
    slug,
    content,
    readingTime: Math.ceil(stats.minutes),
    wordCount: stats.words,
  };
}

// ── Public API ────────────────────────────────────────────────────────────────

export function getArticleBySlug(subDir: string, slug: string): Article | null {
  const cache = getCompiledCache();
  if (cache) {
    return (cache[subDir]?.[slug] as Article) ?? null;
  }
  return readArticleFromFs(subDir, slug);
}

export function getAllArticles(subDir: string): Article[] {
  const cache = getCompiledCache();
  if (cache) {
    const section = cache[subDir];
    if (!section) return [];
    return (Object.values(section) as Article[]).sort(
      (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
    );
  }

  // Filesystem fallback
  const dir = getContentDir(subDir);
  const files = getMdxFiles(dir);
  return files
    .map((file) => readArticleFromFs(subDir, file.replace(/\.mdx$/, '')))
    .filter((a): a is Article => a !== null)
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());
}

/**
 * Returns every article whose section key starts with `${prefix}/`
 * (e.g. prefix="parenting" → parenting/sleep, parenting/feeding, …) plus any
 * articles filed directly under `prefix`.  Each result is annotated with the
 * full `section` it came from so callers can build the correct URL, e.g.
 *   `/${article.section}/${article.slug}` → /parenting/sleep/my-slug
 * Sorted newest-first.
 */
export function getAllArticlesUnder(prefix: string): Array<Article & { section: string }> {
  const cache = getCompiledCache();
  const out: Array<Article & { section: string }> = [];

  if (cache) {
    for (const section of Object.keys(cache)) {
      if (section === prefix || section.startsWith(`${prefix}/`)) {
        for (const article of Object.values(cache[section])) {
          out.push({ ...(article as Article), section });
        }
      }
    }
  } else {
    // Filesystem fallback (local dev): walk immediate sub-directories of content/{prefix}
    const base = getContentDir(prefix);
    if (fs.existsSync(base)) {
      for (const a of getAllArticles(prefix)) out.push({ ...a, section: prefix });
      for (const entry of fs.readdirSync(base, { withFileTypes: true })) {
        if (entry.isDirectory()) {
          const section = `${prefix}/${entry.name}`;
          for (const a of getAllArticles(section)) out.push({ ...a, section });
        }
      }
    }
  }

  return out.sort(
    (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
  );
}

export function getRelatedArticles(current: Article, all: Article[], limit = 3): Article[] {
  return all
    .filter((a) => a.slug !== current.slug)
    .map((a) => ({
      article: a,
      score: a.tags.filter((t) => current.tags.includes(t)).length,
    }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.article);
}

export function getAllSlugs(subDir: string): string[] {
  const cache = getCompiledCache();
  if (cache) {
    return Object.keys(cache[subDir] ?? {});
  }

  const dir = getContentDir(subDir);
  const files = getMdxFiles(dir);
  return files.map((f) => f.replace(/\.mdx$/, ''));
}
