/**
 * Server-side access to SSA baby-name popularity statistics.
 *
 * ⚠️  SERVER ONLY. Do not import this from a client component, and do not
 * import it into src/lib/baby-names.ts — that module is pulled into the client
 * bundle by BabyNamesBrowser, so importing name-stats.json there would ship
 * ~2.6 MB of JSON to every visitor. The /baby-names/[name] route is
 * force-static, so this is read at build time only and baked into the HTML.
 *
 * Data is generated by scripts/build-name-stats.mjs from the US Social Security
 * Administration's public-domain dataset (1880-2025).
 */

/** One observation: [year, births]. Per-point rank is deliberately not stored —
 * only peak/latest ranks are ever rendered, and carrying a third number per
 * point inflated the dataset by a third for no benefit. */
export type StatPoint = [number, number];

export interface SexStats {
  series: StatPoint[];
  peak: { year: number; count: number; rank: number };
  latest: { year: number; count: number; rank: number };
  firstSeen: number;
  totalBabies: number;
  rank5YearsAgo: number | null;
  rank10YearsAgo: number | null;
}

export interface NameStats {
  name: string;
  primary: 'F' | 'M';
  f?: SexStats;
  m?: SexStats;
  /** % of all-time births of this name that were female (100 = girls only) */
  splitF: number;
}

interface StatsFile {
  meta: { source: string; license: string; firstYear: number; latestYear: number; generated: string };
  names: Record<string, NameStats>;
}

// Read from disk rather than import/require. A static `require` is resolved by
// the bundler and INLINED into the Cloudflare Worker script — that blew past
// Cloudflare's 3 MiB Worker size limit and failed the deploy outright
// (handler.mjs hit 12.5 MB). Every route that reads this is prerendered, so the
// read only ever happens at build time in Node, never on the edge. This is the
// same build-time-fs pattern src/app/sitemap.ts already relies on.
const EMPTY: StatsFile = {
  meta: { source: 'US Social Security Administration', license: 'Public domain (CC0)', firstYear: 1880, latestYear: 2025, generated: '' },
  names: {},
};

let _data: StatsFile | null = null;
function getData(): StatsFile {
  if (!_data) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const fs = require('node:fs') as typeof import('node:fs');
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const path = require('node:path') as typeof import('node:path');
      const file = path.join(process.cwd(), 'src', 'data', 'name-stats.json');
      _data = JSON.parse(fs.readFileSync(file, 'utf8')) as StatsFile;
    } catch {
      // Never let a missing/unreadable dataset take the whole page down. If this
      // is ever reached outside a build (e.g. the route loses force-static and
      // renders in the Worker, where fs doesn't exist), the page degrades to the
      // name, meaning and quick facts instead of rendering an empty shell.
      _data = EMPTY;
    }
  }
  return _data;
}

export function getNameStats(slug: string): NameStats | null {
  return getData().names[slug.toLowerCase()] ?? null;
}

export interface TopName {
  slug: string;
  name: string;
  /** The SSA's own national rank for the latest year — not a rank recomputed
   *  over this dataset's 1,085-name subset. */
  rank: number;
  births: number;
  trend: Trend;
  move: string | null;
  /** 5-year rank change; positive = climbed. null when there is no comparison
   *  point. Exposed so copy that says "fastest" can sort by it rather than
   *  approximating with current rank. */
  gain: number | null;
}

/**
 * The most popular names of the dataset's latest year, straight from the SSA's
 * national ranking.
 *
 * Exists because /baby-names/top-100 previously carried a hand-typed ranking
 * that had drifted from this dataset — it listed Charlotte at #8 when the SSA
 * had her at #2, and Mason at #9 against an actual #36, while the page told
 * readers the ranking came from SSA birth-certificate data. One source of truth
 * or none.
 *
 * Build-time only: getData() reads from disk (see the note on it above).
 */
export function getTopNames(sex: 'F' | 'M', limit: number): TopName[] {
  const { names, meta } = getData();
  const key = sex === 'F' ? 'f' : 'm';
  const out: TopName[] = [];
  for (const [slug, d] of Object.entries(names)) {
    const st = d[key];
    // Skip names absent from the latest year: their `latest` describes an
    // earlier year and would rank against a different cohort.
    if (!st || st.latest.year !== meta.latestYear) continue;
    out.push({
      slug,
      name: d.name,
      rank: st.latest.rank,
      births: st.latest.count,
      trend: computeTrend(st),
      move: describeMove(st),
      gain: st.rank5YearsAgo == null ? null : st.rank5YearsAgo - st.latest.rank,
    });
  }
  return out.sort((a, b) => a.rank - b.rank).slice(0, limit);
}

export function getStatsMeta() {
  return getData().meta;
}

/** The series a page should lead with, based on how the name is catalogued. */
export function primaryStats(stats: NameStats): SexStats {
  return (stats.primary === 'F' ? stats.f : stats.m) as SexStats;
}

export type Trend = 'rising' | 'falling' | 'stable' | 'unknown';

/**
 * Trend computed from real rank movement over the last 5 years of data —
 * replaces the hand-authored `popularityTrend` field, which was an unverified
 * assertion. Lower rank number = more popular, so a falling number is a rise.
 */
export function computeTrend(s: SexStats): Trend {
  const past = s.rank5YearsAgo;
  if (past == null) return 'unknown';
  const delta = past - s.latest.rank;
  const threshold = Math.max(5, Math.round(past * 0.1));
  if (delta > threshold) return 'rising';
  if (delta < -threshold) return 'falling';
  return 'stable';
}

/** Formats a rank move into plain language, e.g. "up from #62 five years ago". */
export function describeMove(s: SexStats): string | null {
  const past = s.rank5YearsAgo;
  if (past == null || past === s.latest.rank) return null;
  const dir = past > s.latest.rank ? 'up' : 'down';
  return `${dir} from #${past.toLocaleString()} five years ago`;
}
