/**
 * Server-side access to SSA baby-name popularity statistics.
 *
 * ⚠️  SERVER ONLY. Do not import this from a client component, and do not
 * import it into src/lib/baby-names.ts — that module is pulled into the client
 * bundle by BabyNamesBrowser, so importing name-stats.json there would ship
 * ~2.6 MB of JSON to every visitor. The /baby-names/[name] route is
 * force-static, so this is read at build time only and baked into the HTML.
 *
 * Data is generated by scripts/build-name-stats.mjs from the US Social Security
 * Administration's public-domain dataset (1880-2025).
 */

/** One observation: [year, births, rank within sex that year] */
export type StatPoint = [number, number, number];

export interface SexStats {
  series: StatPoint[];
  peak: { year: number; count: number; rank: number };
  latest: { year: number; count: number; rank: number };
  firstSeen: number;
  totalBabies: number;
  rank5YearsAgo: number | null;
  rank10YearsAgo: number | null;
}

export interface NameStats {
  name: string;
  primary: 'F' | 'M';
  f?: SexStats;
  m?: SexStats;
  /** % of all-time births of this name that were female (100 = girls only) */
  splitF: number;
}

interface StatsFile {
  meta: { source: string; license: string; firstYear: number; latestYear: number; generated: string };
  names: Record<string, NameStats>;
}

// Lazy require (not a top-level import) for the same reason as baby-names.ts:
// keeps the 2.6 MB parse off the Worker cold-start path, and avoids TypeScript
// inferring a vast literal type from the JSON.
let _data: StatsFile | null = null;
function getData(): StatsFile {
  if (!_data) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    _data = require('@/data/name-stats.json') as StatsFile;
  }
  return _data;
}

export function getNameStats(slug: string): NameStats | null {
  return getData().names[slug.toLowerCase()] ?? null;
}

export function getStatsMeta() {
  return getData().meta;
}

/** The series a page should lead with, based on how the name is catalogued. */
export function primaryStats(stats: NameStats): SexStats {
  return (stats.primary === 'F' ? stats.f : stats.m) as SexStats;
}

export type Trend = 'rising' | 'falling' | 'stable' | 'unknown';

/**
 * Trend computed from real rank movement over the last 5 years of data —
 * replaces the hand-authored `popularityTrend` field, which was an unverified
 * assertion. Lower rank number = more popular, so a falling number is a rise.
 */
export function computeTrend(s: SexStats): Trend {
  const past = s.rank5YearsAgo;
  if (past == null) return 'unknown';
  const delta = past - s.latest.rank;
  const threshold = Math.max(5, Math.round(past * 0.1));
  if (delta > threshold) return 'rising';
  if (delta < -threshold) return 'falling';
  return 'stable';
}

/** Formats a rank move into plain language, e.g. "up from #62 five years ago". */
export function describeMove(s: SexStats): string | null {
  const past = s.rank5YearsAgo;
  if (past == null || past === s.latest.rank) return null;
  const dir = past > s.latest.rank ? 'up' : 'down';
  return `${dir} from #${past.toLocaleString()} five years ago`;
}
