import { NextRequest, NextResponse } from 'next/server';
import Fuse from 'fuse.js';
import searchIndex from '@/data/search-index.json';

// Cloudflare Pages edge runtime.
// This route imports a pre-built static JSON index (generated by
// scripts/build-search-index.ts during `npm run build`).
// No fs/path calls at runtime — fully compatible with Cloudflare Workers.
export const runtime = 'edge';

interface SearchItem {
  title: string;
  description: string;
  href: string;
  type: 'article' | 'product' | 'week' | 'tool';
}

const items = searchIndex as SearchItem[];

// Fuse instance is created once at module load (cached for the Worker lifetime)
const fuse = new Fuse(items, {
  keys: [
    { name: 'title', weight: 0.7 },
    { name: 'description', weight: 0.3 },
  ],
  threshold: 0.35,
  includeScore: true,
  minMatchCharLength: 2,
});

export async function GET(req: NextRequest) {
  const q = req.nextUrl.searchParams.get('q')?.trim();

  if (!q || q.length < 2) {
    return NextResponse.json({ results: [] });
  }

  const raw = fuse.search(q, { limit: 20 });
  const results = raw.map((r) => r.item);

  return NextResponse.json({ results }, {
    headers: {
      'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=600',
    },
  });
}
