// Strip any accidental trailing slash from the env var so all canonical URLs
// and sitemap entries are consistent: https://pregnancysprout.com/blog (not /blog/)
const rawUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://pregnancysprout.com';
const siteUrl = rawUrl.endsWith('/') ? rawUrl.slice(0, -1) : rawUrl;

export const siteConfig = {
  name: 'PregnancySprout',
  tagline: 'Your Complete Pregnancy & Baby Guide',
  description:
    'Expert guides on pregnancy week by week, baby names, product reviews, and parenting tips. Everything you need for your journey to parenthood.',
  url: siteUrl,
  // Dynamic OG image generated by src/app/opengraph-image.tsx (ImageResponse).
  // The route /opengraph-image returns a branded 1200×630 PNG at edge runtime.
  // Never reference the old /og-default.jpg — that file does not exist.
  ogImage: `${siteUrl}/opengraph-image`,
  email: 'hello@pregnancysprout.com',
  // Social media profiles — used in Footer and JSON-LD sameAs.
  // ONLY list profiles that actually exist. Every entry here is emitted to
  // Google as an Organization "sameAs", i.e. a claim that this profile is us.
  // Four dead handles (twitter/facebook/instagram/youtube) were listed here and
  // rendered as footer links that 404'd. Do not add a platform before the
  // account is live.
  social: {
    pinterest: 'https://pinterest.com/pregnancysprout',
    linkedin:  'https://www.linkedin.com/in/sandeep-singsarva',
  },
  authors: [{ name: 'Sandeep Singsarva', url: 'https://pregnancysprout.com/authors/sandeep-singsarva' }],
  keywords: [
    'pregnancy',
    'baby',
    'parenting',
    'baby names',
    'pregnancy week by week',
    'baby products',
    'baby development',
    'newborn',
    'toddler',
  ],
};
