import { readFileSync, writeFileSync } from 'fs';

const existing = JSON.parse(readFileSync('src/data/baby-names.json', 'utf8'));
const existingNames = new Set(existing.map(e => e.name.toLowerCase() + '-' + e.gender));
let nextId = existing.length + 1;

const n = (name, gender, origin, meaning, rank, trend, syllables, tags, related, nicknames) => {
  const key = name.toLowerCase() + '-' + gender;
  if (existingNames.has(key)) return null;
  return { id: String(nextId++), name, gender, origin, meaning, popularityRank: rank, popularityTrend: trend, syllables, startingLetter: name[0], tags, relatedNames: related, nicknames };
};

const add = (...args) => { const r = n(...args); return r; };

const more = [
  // More Girls
  add('Abbigail','girl',['Hebrew'],'father is joyful',200,'stable',4,['biblical','vintage'],['Abigail','Abbey'],['Abby']),
  add('Adaline','girl',['French','Germanic'],'noble',90,'rising',4,['vintage','elegant'],['Adeline','Adelaide'],['Addie']),
  add('Adalynn','girl',['Germanic'],'noble',110,'rising',4,['modern','elegant'],['Adeline','Adaline'],['Addie']),
  add('Addison','girl',['English'],'son of Adam',25,'stable',3,['modern','popular'],['Madison','Emerson'],['Addie']),
  add('Adley','girl',['Hebrew'],'just, fair',115,'rising',3,['hebrew','modern'],['Hadley','Adley'],['Ad']),
  add('Adrienne','girl',['French','Latin'],'from Hadria',105,'stable',3,['french','classic'],['Adriana','Andrea'],[]),
  add('Agatha','girl',['Greek'],'good woman',135,'rising',3,['greek','vintage','saint'],['Agnes','Agata'],['Aggie']),
  add('Albertine','girl',['Germanic'],'noble and bright',190,'rising',4,['germanic','vintage'],['Alberta','Alberte'],['Albie']),
  add('Alcyone','girl',['Greek'],'kingfisher',220,'rare',4,['greek','mythological','rare'],['Halcyon','Cyone'],[]),
  add('Alena','girl',['Slavic'],'bright, beautiful',115,'rising',3,['slavic','elegant'],['Alina','Elena'],[]),
  add('Alessandra','girl',['Italian','Greek'],'defending men',80,'rising',4,['italian','elegant'],['Alexandra','Sandra'],['Sandra','Alessa']),
  add('Alexandra','girl',['Greek'],'defending men',30,'stable',5,['classic','royal'],['Alexa','Sandra'],['Alex','Sandy']),
  add('Alondra','girl',['Spanish'],'lark',96,'stable',3,['spanish','nature'],['Alejandra','Sandra'],[]),
  add('Alora','girl',['African'],'my dream',112,'rising',3,['african','modern'],['Alara','Aurora'],[]),
  add('Alva','girl',['Norse','Spanish'],'elf, white',145,'rising',2,['norse','vintage'],['Elva','Alba'],[]),
  add('Alvina','girl',['Germanic'],'elf friend',165,'rare',3,['germanic','vintage'],['Alvinia','Elvina'],[]),
  add('Amara','girl',['African','Sanskrit'],'grace, eternal',52,'rising',3,['african','modern','elegant'],['Amara','Amari'],['Mara']),
  add('Amari','girl',['Hebrew','African'],'eternal',60,'rising',3,['hebrew','african','modern'],['Amara','Amaru'],[]),
  add('Amaya','girl',['Japanese','Basque'],'night rain, end',68,'rising',3,['japanese','basque','modern'],['Maya','Amara'],['Maya']),
  add('Ambrose','girl',['Latin'],'immortal',190,'rare',2,['latin','vintage','rare'],['Amber','Ambra'],[]),
  add('Amelia','girl',['Germanic','Latin'],'work, industrious',7,'rising',4,['classic','popular'],['Amelie','Emily'],['Amy','Mia','Millie']),
  add('Amie','girl',['French'],'beloved',140,'stable',2,['french','sweet'],['Amy','Aimee','Amie'],[]),
  add('Amina','girl',['Arabic'],'trustworthy, faithful',85,'rising',3,['arabic','popular'],['Amin','Amena'],[]),
  add('Amira','girl',['Arabic','Hebrew'],'princess, treetop',75,'rising',3,['arabic','hebrew','elegant'],['Amara','Emira'],[]),
  add('Anastasiya','girl',['Russian'],'resurrection',165,'stable',6,['russian','elegant'],['Anastasia','Stasia'],[]),
  add('Anaya','girl',['Sanskrit','African'],'completely free',58,'rising',3,['sanskrit','african','modern'],['Aniyah','Naya'],['Naya']),
  add('Andromeda','girl',['Greek'],'ruler of men',140,'rising',4,['greek','mythological','celestial'],['Andromeda','Andie'],['Andie']),
  add('Angelina','girl',['Greek','Latin'],'angel',67,'stable',4,['greek','elegant','popular'],['Angela','Angel'],['Angie','Lina']),
  add('Anika','girl',['Sanskrit','Swedish'],'grace',98,'rising',3,['sanskrit','swedish','elegant'],['Annika','Anica'],[]),
  add('Annika','girl',['Swedish'],'grace',92,'rising',3,['swedish','nordic','elegant'],['Anika','Anna'],[]),
  add('Anona','girl',['Latin'],'pineapple, annual',195,'rare',3,['latin','rare','vintage'],['Anona','Nona'],[]),
  add('Antigone','girl',['Greek'],'against birth',190,'rare',4,['greek','mythological','rare'],['Antone','Ione'],[]),
  add('Antonella','girl',['Italian'],'priceless one',108,'rising',4,['italian','elegant'],['Antonia','Toni'],['Nella','Toni']),
  add('Antonia','girl',['Latin'],'priceless one',98,'stable',4,['roman','classic','vintage'],['Toni','Antoinette'],['Toni','Tonya']),
  add('Aoife','girl',['Irish'],'beautiful, radiant',78,'rising',3,['irish','gaelic','beautiful'],['Eve','Ava','Eva'],[]),
  add('Apollonia','girl',['Greek'],'of Apollo',160,'rare',5,['greek','mythological','rare'],['Apollo','Apolline'],[]),
  add('Arabella','girl',['Latin'],'yielding to prayer',60,'rising',4,['latin','romantic','vintage'],['Isabella','Arabella'],['Bella','Ara']),
  add('Arcadia','girl',['Greek'],'paradise, utopia',140,'rising',4,['greek','mythological'],['Ariadne','Arcadia'],[]),
  add('Ariadne','girl',['Greek'],'most holy',105,'rising',4,['greek','mythological','elegant'],['Ariadna','Aria'],['Aria']),
  add('Ariel','girl',['Hebrew'],'lion of God',70,'stable',3,['biblical','literary'],['Arielle','Aria'],[]),
  add('Ariella','girl',['Hebrew'],'lioness of God',80,'rising',4,['biblical','elegant'],['Ariel','Aria'],['Ari','Ella']),
  add('Arienne','girl',['French'],'holy',115,'rising',3,['french','elegant'],['Ariane','Arianne'],[]),
  add('Arlene','girl',['Celtic'],'pledge',125,'stable',2,['celtic','vintage'],['Arline','Arlena','Karla'],[]),
  add('Armelle','girl',['French','Celtic'],'princess, bear',150,'rare',2,['french','celtic','rare'],['Armel','Armine'],[]),
  add('Artemis','girl',['Greek'],'goddess of the hunt',88,'rising',3,['greek','goddess','mythological'],['Artemia','Artemisia'],[]),
  add('Arwen','girl',['Welsh'],'noble maiden',105,'rising',2,['welsh','literary','elvish'],['Bronwen','Eirwen'],[]),
  add('Aspen','girl',['English'],'aspen tree',72,'rising',2,['nature','place','modern'],['Aspyn','Jasmine'],['Asp']),
  add('Asteria','girl',['Greek'],'star',115,'rising',4,['greek','celestial'],['Astrid','Estelle'],[]),
  add('Aurelia','girl',['Latin'],'golden',70,'rising',4,['latin','roman','elegant'],['Aurora','Aurelie'],['Aura','Lia']),
  add('Aurelie','girl',['French'],'golden',95,'rising',3,['french','elegant'],['Aurelia','Aurora'],[]),
  add('Avalon','girl',['Celtic'],'island of apples',90,'rising',3,['celtic','mythological','magical'],['Evelyn','Avery'],[]),
  add('Aviana','girl',['Latin'],'bird-like',85,'rising',4,['latin','modern'],['Ava','Avianna'],[]),
  add('Avigail','girl',['Hebrew'],'father is joyful',180,'rare',3,['hebrew','biblical','rare'],['Abigail','Aviva'],[]),
  add('Aviva','girl',['Hebrew'],'spring',130,'rising',3,['hebrew','nature'],['Viva','Avi'],[]),
  add('Axelle','girl',['Germanic'],'father of peace',125,'rising',2,['germanic','french'],['Axel','Axelle'],[]),
  add('Ayasha','girl',['Native American'],'little one',145,'rising',3,['native american','soft'],['Ayasha','Aisha'],[]),
  add('Azalea','girl',['Greek'],'dry, flower',80,'rising',4,['greek','flower','nature'],['Azaleia','Azalee'],['Aza']),
  add('Azure','girl',['French'],'sky blue',115,'rising',2,['french','colour','nature'],['Azura','Skye'],[]),
  add('Bea','girl',['Latin'],'bringer of happiness',120,'rising',2,['latin','short','sweet'],['Beatrice','Beatrix'],[]),
  add('Bernadette','girl',['Germanic'],'brave as a bear',115,'rising',3,['germanic','religious','vintage'],['Bernadine','Bernie'],['Bernie','Bern']),
  add('Bernice','girl',['Greek'],'bringer of victory',130,'stable',2,['greek','vintage','biblical'],['Berenice','Bernie'],['Bernie']),
  add('Blossom','girl',['English'],'flower, blossom',130,'rising',2,['nature','flower','sweet'],['Blossom','Bloom'],[]),
  add('Blythe','girl',['English'],'happy, carefree',105,'rising',1,['english','virtue','vintage'],['Blythe','Brithe'],[]),
  add('Bobbie','girl',['Germanic'],'bright fame',120,'stable',2,['germanic','vintage'],['Barbara','Bobbi','Bobby'],[]),
  add('Bria','girl',['Irish'],'power, virtue',95,'rising',3,['irish','short','modern'],['Brianna','Bree','Bri'],[]),
  add('Briana','girl',['Irish'],'strong, virtuous',50,'stable',3,['irish','strong'],['Brianna','Bria'],['Bri']),
  add('Brigitte','girl',['French','Irish'],'strength',95,'stable',2,['french','irish','elegant'],['Bridget','Brigid'],['Bri','Britt']),
  add('Bronwyn','girl',['Welsh'],'white breast',105,'rising',2,['welsh','vintage'],['Bronwen','Bronwyn'],[]),
  add('Brunhilde','girl',['Norse'],'armoured battle maid',200,'rare',3,['norse','legendary','rare'],['Brunhild','Brynhild'],[]),
  add('Cadence','girl',['Latin'],'rhythm, flow',75,'rising',3,['latin','musical','modern'],['Kadence','Cadence'],[]),
  add('Caitlin','girl',['Irish'],'pure',70,'stable',2,['irish','classic'],['Katelyn','Caitlyn'],['Cait']),
  add('Calliope','girl',['Greek'],'beautiful voice',95,'rising',4,['greek','muse','musical'],['Callie','Calypso'],['Callie']),
  add('Calypso','girl',['Greek'],'she who hides',108,'rising',3,['greek','mythological','musical'],['Calliope','Calyps'],[]),
  add('Camelia','girl',['Latin'],'camellia flower',100,'rising',4,['latin','flower'],['Camille','Camellia'],[]),
  add('Camellia','girl',['Latin'],'camellia flower',95,'rising',4,['latin','flower','elegant'],['Camelia','Camille'],[]),
  add('Caprice','girl',['French'],'whim, impulse',140,'stable',2,['french','spirited'],['Capri','April'],[]),
  add('Carmen','girl',['Spanish','Latin'],'garden, song',85,'stable',2,['spanish','musical','classic'],['Karmen','Carmine'],[]),
  add('Cassia','girl',['Greek','Latin'],'cinnamon tree',100,'rising',3,['greek','nature'],['Kezia','Cassie'],[]),
  add('Cassidy','girl',['Irish'],'curly-haired',75,'stable',3,['irish','modern'],['Cassandra','Cassie'],['Cass']),
  add('Caterina','girl',['Italian','Greek'],'pure',92,'rising',4,['italian','elegant'],['Catherine','Katerina'],['Cate','Rina']),
  add('Catrina','girl',['Scottish'],'pure',110,'stable',3,['scottish','gaelic'],['Catherine','Katrina'],['Cat']),
  add('Cecily','girl',['Latin'],'blind',98,'rising',3,['latin','vintage','elegant'],['Cecilia','Cece'],['Cece','Cis']),
  add('Cerys','girl',['Welsh'],'love',99,'rising',2,['welsh','gaelic'],['Ceris','Cerys'],[]),
  add('Chandra','girl',['Sanskrit'],'moon goddess',105,'stable',2,['sanskrit','goddess','lunar'],['Sandra','Chanda'],[]),
  add('Chantal','girl',['French'],'stone, boulder',115,'stable',2,['french','classic'],['Chantel','Shantel'],[]),
  add('Charity','girl',['English'],'giving, kindness',110,'stable',3,['virtue','religious','classic'],['Faith','Hope'],[]),
  add('Chiara','girl',['Italian'],'bright, clear',82,'rising',3,['italian','elegant'],['Kiara','Ciara','Clara'],[]),
  add('Chloe','girl',['Greek'],'blooming',9,'stable',2,['greek','popular'],['Zoe','Cleo'],[]),
  add('Ciara','girl',['Irish'],'dark-haired',82,'stable',3,['irish','gaelic','dark'],['Kiara','Kiera'],[]),
  add('Claiborne','girl',['English'],'boundary by clay',190,'rare',2,['english','rare','place'],['Claire','Clairborne'],[]),
  add('Cleo','girl',['Greek'],'glory, fame',88,'rising',2,['greek','vintage','short'],['Cleopatra','Clio','Clara'],[]),
  add('Cleopatra','girl',['Greek'],'glory of the father',110,'rising',4,['greek','historical','regal'],['Cleo','Patra'],['Cleo']),
  add('Clodagh','girl',['Irish'],'river in Ireland',112,'rising',2,['irish','gaelic'],['Cloda','Clodag'],[]),
  add('Comfort','girl',['English'],'comfort, relief',165,'stable',2,['virtue','english'],['Constance','Content'],[]),
  add('Cora','girl',['Greek'],'maiden',48,'rising',2,['greek','vintage'],['Coral','Coraline','Nora'],[]),
  add('Coral','girl',['Latin','English'],'coral reef',92,'rising',2,['nature','colour','modern'],['Cora','Cori','Coralie'],[]),
  add('Coralie','girl',['French'],'coral',102,'rising',3,['french','elegant','nature'],['Coral','Cora','Coralia'],[]),
  add('Cordelia','girl',['Celtic','Latin'],'heart, daughter of the sea',88,'rising',4,['celtic','literary','elegant'],['Cora','Delia','Della'],['Cora','Delia']),
  add('Cosima','girl',['Italian','Greek'],'order, beauty',105,'rising',3,['italian','artistic'],['Cosma','Cosmos'],[]),
  add('Cressida','girl',['Greek'],'gold',115,'rising',3,['greek','literary'],['Cressa','Cress'],[]),
  add('Cybele','girl',['Phrygian'],'mother goddess',165,'rare',3,['mythological','rare'],['Sybil','Cybele'],[]),
  add('Dagny','girl',['Norse'],'new day',130,'rising',2,['norse','nordic','vintage'],['Dagna','Dagny'],[]),
  add('Dahlia','girl',['Swedish'],'valley, flower',65,'rising',3,['flower','nature','vintage'],['Dalia','Dalia','Daisy'],['Dolly']),
  add('Damaris','girl',['Greek'],'gentle, calf',135,'rising',3,['greek','biblical'],['Tamara','Demi'],[]),
  add('Daria','girl',['Persian','Greek'],'maintains possessions',102,'rising',3,['persian','classic'],['Darya','Darian'],[]),
  add('Darla','girl',['English'],'dear, beloved',120,'stable',2,['english','vintage'],['Darling','Darla'],[]),
  add('Delia','girl',['Greek'],'from Delos',96,'rising',3,['greek','mythological','vintage'],['Cordelia','Deli','Della'],['Della']),
  add('Delphine','girl',['French','Greek'],'dolphin, woman from Delphi',95,'rising',2,['french','greek','elegant'],['Delphi','Daphne'],[]),
  add('Demelza','girl',['Cornish'],'fort of Maeldaf',130,'rising',3,['cornish','celtic','vintage'],['Demi','Melza'],['Demi']),
  add('Demi','girl',['Greek','French'],'half, earth mother',95,'rising',2,['greek','modern'],['Demeter','Naomi'],[]),
  add('Devika','girl',['Sanskrit'],'little goddess',118,'rising',3,['sanskrit','indian'],['Devi','Deviya'],[]),
  add('Devorah','girl',['Hebrew'],'bee',135,'rising',3,['hebrew','biblical'],['Deborah','Devora'],['Debbie']),
  add('Diantha','girl',['Greek'],'divine flower',165,'rare',3,['greek','flower','rare'],['Diana','Dianthe'],[]),
  add('Dido','girl',['Phoenician'],'wanderer',175,'rare',2,['phoenician','historical','rare'],['Dido','Diana'],[]),
  add('Dolores','girl',['Spanish'],'sorrows',115,'stable',3,['spanish','religious','vintage'],['Lola','Delores'],['Lola','Dee']),
  add('Dominique','girl',['French'],'of the Lord',92,'stable',3,['french','religious','neutral'],['Dominica','Nicole'],[]),
  add('Donella','girl',['Scottish'],'dark, female warrior',155,'rare',3,['scottish','rare'],['Donna','Donella'],[]),
  add('Donna','girl',['Italian'],'lady',110,'stable',2,['italian','classic'],['Donella','Diana'],[]),
  add('Dora','girl',['Greek'],'gift',145,'rising',2,['greek','vintage'],['Dorothy','Theodora'],['Dori']),
  add('Drucilla','girl',['Latin'],'strong',155,'rare',3,['latin','biblical','rare'],['Drusilla','Dru'],['Dru']),
  add('Dulcie','girl',['Latin'],'sweet',130,'rising',2,['latin','vintage','sweet'],['Dulce','Dulcine'],['Dulce']),
  add('Ebony','girl',['English'],'deep black wood',105,'stable',3,['english','nature','colour'],['Ivory','Ebonee'],[]),
  add('Edina','girl',['English','Scottish'],'prosperous friend',145,'rising',3,['english','scottish'],['Edna','Edina'],[]),
  add('Edwina','girl',['Germanic'],'prosperous friend',135,'rising',3,['germanic','vintage'],['Edwin','Winnie'],['Winnie']),
  add('Effie','girl',['Greek'],'well-spoken',118,'rising',2,['greek','vintage','sweet'],['Euphemia','Effie'],['Effy']),
  add('Eglantine','girl',['French'],'wild rose',170,'rare',3,['french','flower','rare'],['Rose','Eglantina'],[]),
  add('Eilish','girl',['Irish'],'pledged to God',88,'rising',2,['irish','gaelic'],['Elizabeth','Ealish'],[]),
  add('Eirene','girl',['Greek'],'peace',115,'rising',3,['greek','goddess','peace'],['Irene','Eireen'],[]),
  add('Elara','girl',['Greek'],'happy',92,'rising',3,['greek','celestial'],['Clara','Elena'],[]),
  add('Elea','girl',['Greek'],'sun ray',115,'rising',3,['greek','light'],['Elena','Ellia'],[]),
  add('Eleanora','girl',['French'],'shining light',88,'rising',4,['french','royal','elegant'],['Eleanor','Nora'],['Ellie','Nora']),
  add('Elektra','girl',['Greek'],'amber, shining',105,'rising',3,['greek','mythological'],['Electra','Ellie'],[]),
  add('Eleonora','girl',['Italian'],'shining light',100,'rising',5,['italian','royal'],['Eleanor','Eleonore'],['Ellie','Nora']),
  add('Elfie','girl',['Germanic'],'elf',155,'rare',2,['germanic','rare','sweet'],['Elfriede','Ellie'],[]),
  add('Elfleda','girl',['Germanic'],'elf beauty',200,'rare',3,['germanic','vintage','rare'],['Alfreda','Elfleda'],[]),
  add('Elfriede','girl',['Germanic'],'elf strength',175,'rare',3,['germanic','vintage','rare'],['Elfrida','Elfie'],[]),
  add('Elga','girl',['Norse'],'holy',165,'rare',2,['norse','holy','rare'],['Helga','Olga'],[]),
  add('Eliana','girl',['Hebrew'],'God has answered',41,'rising',4,['hebrew','modern','elegant'],['Eliane','Elena','Ellia'],['Lia','Ellie']),
  add('Elinor','girl',['Welsh'],'bright, shining',96,'rising',3,['welsh','vintage'],['Eleanor','Elinore'],['Ellie','Nell']),
  add('Elisa','girl',['Hebrew'],'my God is an oath',75,'rising',3,['hebrew','italian','elegant'],['Elise','Elizabeth'],['Ellie']),
  add('Elise','girl',['French','Hebrew'],'pledged to God',36,'stable',2,['french','elegant'],['Elisa','Eloise'],['Ellie']),
  add('Elisha','girl',['Hebrew'],'God is my salvation',95,'rising',3,['hebrew','biblical'],['Elisa','Alisha'],[]),
  add('Elissa','girl',['Greek','Hebrew'],'noble, of the noble sort',108,'stable',3,['greek','elegant'],['Elyssa','Melissa'],['Lissy']),
  add('Elke','girl',['Dutch','Low German'],'noble',130,'rising',2,['dutch','vintage'],['Elka','Elke'],[]),
  add('Ella','girl',['Germanic','Hebrew'],'all, completely',8,'stable',2,['popular','elegant'],['Eleanor','Ellie'],['Ellie']),
  add('Ellery','girl',['English'],'cheerful',105,'rising',3,['english','modern'],['Emery','Avery'],[]),
  add('Elodie','girl',['French'],'marsh flower',88,'rising',3,['french','nature','elegant'],['Melodie','Elody'],['Ellie']),
  add('Elowen','girl',['Cornish'],'elm tree',112,'rising',3,['cornish','celtic','nature'],['Rowan','Ellowen'],[]),
  add('Elspeth','girl',['Scottish'],'pledged to God',108,'rising',2,['scottish','gaelic'],['Elizabeth','Elspie'],['Elspie','Elsie']),
  add('Ember','girl',['English'],'spark of fire',78,'rising',2,['nature','element','modern'],['Amber','Emberly'],[]),
  add('Emerald','girl',['English'],'green gemstone',100,'rising',3,['jewel','colour','nature'],['Esmeralda','Emmie'],[]),
  add('Emiliana','girl',['Italian'],'rival',96,'rising',5,['italian','romantic'],['Emilia','Emiliano'],['Emi']),
  add('Emmeline','girl',['French','Germanic'],'whole, universal',72,'rising',3,['french','vintage','elegant'],['Emma','Emmaline'],['Emmy','Emma']),
  add('Endellion','girl',['Cornish'],'soul, spirit',190,'rare',4,['cornish','saint','rare'],['Endell','Endelion'],[]),
  add('Enya','girl',['Irish'],'fire, little seed',92,'rising',2,['irish','musical','modern'],['Anya','Eithne'],[]),
  add('Erica','girl',['Norse'],'eternal ruler',90,'stable',3,['norse','classic'],['Erika','Ericka'],[]),
  add('Erin','girl',['Irish'],'from Ireland',72,'stable',2,['irish','place','classic'],['Eryn','Aryn'],[]),
  add('Ermintrude','girl',['Germanic'],'strength of the whole',225,'rare',3,['germanic','vintage','rare'],['Ermintruda','Trudie'],['Trudie']),
  add('Esme','girl',['French','Persian'],'esteemed, beloved',65,'rising',2,['french','modern','elegant'],['Esmeralda','Esmee'],['Esme']),
  add('Esmeralda','girl',['Spanish'],'emerald',82,'rising',4,['spanish','gemstone','romantic'],['Esme','Emerald'],['Esme']),
  add('Esperanza','girl',['Spanish'],'hope',110,'stable',4,['spanish','virtue'],['Espe','Esperanza'],['Espe']),
  add('Estelle','girl',['French','Latin'],'star',82,'rising',2,['french','celestial','vintage'],['Stella','Estella'],[]),
  add('Esther','girl',['Hebrew','Persian'],'star',76,'rising',2,['biblical','celestial','vintage'],['Ester','Hester'],['Essie']),
  add('Eta','girl',['Hebrew'],'to shine',180,'rare',2,['hebrew','short','rare'],['Eta','Eta'],[]),
  add('Ethelind','girl',['Germanic'],'noble serpent',210,'rare',3,['germanic','vintage','rare'],['Ethel','Adeline'],[]),
  add('Eulalia','girl',['Greek'],'sweet-speaking',135,'rising',4,['greek','saint','vintage'],['Eulalie','Eula'],['Eula']),
  add('Euphemia','girl',['Greek'],'well-spoken',140,'rising',4,['greek','saint','vintage'],['Effie','Euphemie'],['Effie']),
  add('Evangeline','girl',['Greek'],'good news',65,'rising',5,['religious','romantic'],['Evie','Eva'],['Eva','Evie']),
  add('Everleigh','girl',['English'],'ever brave',75,'rising',3,['english','modern'],['Everly','Beverly'],['Evie']),
  add('Everly','girl',['English'],'ever brave',70,'rising',3,['english','modern'],['Everleigh','Beverly'],['Evie']),
  add('Evette','girl',['French'],'yew wood',135,'stable',2,['french','vintage'],['Yvette','Ivette'],[]),
  add('Faye','girl',['English','French'],'fairy, faith',82,'rising',1,['english','vintage','magical'],['Fay','Faith','Faith'],[]),
  add('Fernanda','girl',['Spanish','Germanic'],'bold voyager',99,'stable',3,['spanish','adventurous'],['Fernanda','Nanda'],['Nanda','Fer']),
  add('Fiamma','girl',['Italian'],'flame',140,'rising',3,['italian','nature','fiery'],['Fia','Flame'],[]),
  add('Fifi','girl',['French'],'God will add',120,'rising',3,['french','playful'],['Josephine','Sophie'],[]),
  add('Fleur','girl',['French'],'flower',88,'rising',1,['french','flower','elegant'],['Flora','Florence'],[]),
  add('Flora','girl',['Latin'],'flower',80,'rising',2,['latin','flower','vintage'],['Florence','Fleur','Flower'],['Flo']),
  add('Florentina','girl',['Latin'],'flourishing',130,'rare',4,['latin','vintage'],['Florence','Florentine'],['Flo']),
  add('Flossie','girl',['Latin'],'flourishing',140,'rising',2,['latin','vintage','sweet'],['Florence','Flora'],['Flo']),
  add('Fontaine','girl',['French'],'fountain, water source',160,'rare',2,['french','nature','rare'],['Fontanna','Fawn'],[]),
  add('Galadriel','girl',['Elvish'],'maiden crowned with radiance',145,'rising',4,['literary','elvish','fantasy'],['Gladys','Gala'],[]),
  add('Garnet','girl',['English'],'dark red gemstone',110,'rising',2,['jewel','nature','colour'],['Garnett','Ruby'],['Garnie']),
  add('Genevra','girl',['Italian','Celtic'],'white wave',115,'rising',3,['italian','celtic'],['Guinevere','Geneva'],[]),
  add('Genna','girl',['Welsh'],'white shadow',120,'stable',2,['welsh','modern'],['Jenna','Gwen'],[]),
  add('Georgette','girl',['French'],'farmer',108,'stable',2,['french','vintage'],['Georgia','Georgina'],['Georgie']),
  add('Gertrude','girl',['Germanic'],'spear of strength',130,'rising',2,['germanic','vintage'],['Greta','Trudie'],['Trudie','Gertie']),
  add('Giovanna','girl',['Italian'],'God is gracious',96,'rising',3,['italian','biblical'],['Gianna','Gio'],['Gio']),
  add('Giselle','girl',['Germanic'],'pledge',88,'rising',2,['germanic','french','elegant'],['Gisele','Gisella'],['Gigi']),
  add('Gladys','girl',['Welsh'],'land, nation',115,'rising',2,['welsh','vintage'],['Gwen','Gwyneth'],[]),
  add('Glenna','girl',['Scottish','Irish'],'valley',120,'stable',2,['scottish','nature'],['Glenn','Glenna'],[]),
  add('Glinda','girl',['Welsh'],'holy, good',150,'rare',2,['welsh','literary','magical'],['Glenda','Linda'],[]),
  add('Gloriosa','girl',['Latin'],'glorious',175,'rare',4,['latin','floral','rare'],['Gloria','Gloriana'],[]),
  add('Greta','girl',['Germanic'],'pearl',90,'rising',2,['german','nordic','vintage'],['Margaret','Margot'],[]),
  add('Griselda','girl',['Germanic'],'grey battle maid',155,'rare',3,['germanic','vintage','rare'],['Grisella','Griselda'],['Gris','Zelda']),
  add('Gunnhild','girl',['Norse'],'war battle',185,'rare',2,['norse','warrior','rare'],['Gunnhildr','Hild'],[]),
  add('Gwendolyn','girl',['Welsh'],'white ring',95,'rising',3,['welsh','vintage'],['Gwen','Gwendoline'],['Gwen','Wendy']),
  add('Gwenllian','girl',['Welsh'],'white flaxen',160,'rare',3,['welsh','rare','royal'],['Gwen','Gwenlian'],[]),
  add('Halcyon','girl',['Greek'],'kingfisher, peaceful',115,'rising',3,['greek','nature','peaceful'],['Alcyone','Halcion'],[]),
  add('Hana','girl',['Japanese','Arabic'],'flower, happiness, grace',90,'rising',2,['japanese','arabic'],['Hannah','Hanna'],[]),
  add('Hanako','girl',['Japanese'],'flower child',118,'rising',4,['japanese','flower','sweet'],['Hana','Hanae'],[]),
  add('Hannelore','girl',['Germanic'],'grace and mercy',140,'stable',3,['germanic','german','vintage'],['Hanna','Lore'],[]),
  add('Harmonia','girl',['Greek'],'harmony',110,'rising',4,['greek','goddess','musical'],['Harmony','Hermione'],[]),
  add('Harmony','girl',['English'],'musical unity',74,'stable',3,['musical','virtue','modern'],['Harmonia','Melody'],[]),
  add('Hebe','girl',['Greek'],'youth',140,'rising',2,['greek','goddess','youth'],['Heba','Hebi'],[]),
  add('Hecate','girl',['Greek'],'will, far-off, witch',155,'rare',3,['greek','goddess','magical'],['Hekate','Cate'],[]),
  add('Hedwig','girl',['Germanic'],'combat, war',160,'rare',2,['germanic','literary','vintage'],['Hedda','Hedvika'],['Heddie']),
  add('Hedy','girl',['Germanic'],'combat',140,'rising',2,['germanic','vintage','short'],['Hedwig','Heidi'],[]),
  add('Heidi','girl',['Germanic'],'noble, of noble birth',78,'stable',2,['german','nordic','popular'],['Heide','Adalheid'],[]),
  add('Heloise','girl',['French'],'healthy, wide',88,'rising',3,['french','literary','vintage'],['Louise','Eloise'],[]),
  add('Hera','girl',['Greek'],'protector, queen',98,'rising',2,['greek','goddess','strong'],['Hera','Juno'],[]),
  add('Hermia','girl',['Greek'],'messenger',115,'rising',3,['greek','literary'],['Hermione','Erma'],[]),
  add('Hermione','girl',['Greek'],'messenger of the gods',88,'rising',4,['greek','literary','magical'],['Hermia','Ermine'],['Hermie']),
  add('Hestia','girl',['Greek'],'hearth, fireside',105,'rising',3,['greek','goddess'],['Hestia','Estelle'],[]),
  add('Hilde','girl',['Norse'],'battle maid',125,'rising',2,['norse','strong','vintage'],['Hilda','Hildegard'],[]),
  add('Hildegard','girl',['Germanic'],'battle strength',145,'rising',3,['germanic','saint','vintage'],['Hilde','Hildy'],['Hildy']),
  add('Honey','girl',['English'],'sweet nectar',115,'rising',2,['english','sweet','nature'],['Bonnie','Sunny'],[]),
  add('Honoria','girl',['Latin'],'honour',130,'rising',4,['latin','virtue','vintage'],['Honor','Nora'],['Nora']),
  add('Hypatia','girl',['Greek'],'highest',145,'rare',4,['greek','historical','academic'],['Hypatia','Hippa'],[]),
  add('Ianthe','girl',['Greek'],'violet flower',135,'rare',2,['greek','flower','rare'],['Violet','Anthea'],[]),
  add('Idalia','girl',['Italian','Greek'],'behold the sun',150,'rare',4,['italian','rare'],['Idala','Ida'],[]),
  add('Idina','girl',['Germanic'],'industrious',150,'rare',3,['germanic','musical','rare'],['Edina','Dina'],[]),
  add('Ilaria','girl',['Italian'],'cheerful',110,'rising',4,['italian','cheerful'],['Hilary','Ilaria'],[]),
  add('Iliana','girl',['Greek'],'from Ilion, Troy',105,'rising',4,['greek','classical'],['Eliana','Ileana'],['Liana']),
  add('Illyana','girl',['Slavic'],'bright',108,'rising',4,['slavic','modern'],['Ilyana','Illiana'],['Lily']),
  add('Imani','girl',['Swahili'],'faith',88,'rising',3,['swahili','african','virtue'],['Amani','Imani'],[]),
  add('Ingeborg','girl',['Norse'],'Ing\'s fortress',160,'rare',3,['norse','vintage','rare'],['Inga','Ingrid'],[]),
  add('Iona','girl',['Scottish'],'purple jewel, island',99,'rising',3,['scottish','place','nature'],['Ione','Fiona'],[]),
  add('Ione','girl',['Greek'],'violet flower',118,'rising',2,['greek','flower','vintage'],['Iona','Io'],[]),
  add('Irene','girl',['Greek'],'peace',95,'rising',3,['greek','goddess','vintage'],['Eirene','Irina'],['Rene']),
  add('Irina','girl',['Russian'],'peace',100,'stable',3,['russian','elegant'],['Irene','Rina'],[]),
  add('Isadora','girl',['Greek'],'gift of Isis',100,'rising',4,['greek','mythological','elegant'],['Isidora','Dora'],['Dora','Izzy']),
  add('Isolde','girl',['Celtic'],'ice ruler',108,'rising',2,['celtic','arthurian','romantic'],['Iseult','Yseult'],[]),
  add('Jocasta','girl',['Greek'],'shining moon',145,'rare',3,['greek','mythological','rare'],['Jocelyn','Casta'],[]),
  add('Jocelyn','girl',['Germanic'],'joyous',74,'stable',3,['germanic','popular'],['Joslyn','Joci'],['Joce','Josie']),
  add('Johanna','girl',['Hebrew'],'God is gracious',95,'rising',3,['hebrew','classic','scandinavian'],['Joanna','Jana'],['Jo']),
  add('Jolie','girl',['French'],'pretty',96,'rising',2,['french','cheerful'],['Jolee','Jolene'],[]),
  add('Jolene','girl',['American'],'God will increase',105,'stable',2,['american','musical'],['Jolie','Joline'],[]),
  add('Jora','girl',['Hebrew'],'autumn rain',145,'rare',2,['hebrew','nature','rare'],['Jordan','Jora'],[]),
  add('Judith','girl',['Hebrew'],'woman of Judea',108,'stable',2,['biblical','classic','vintage'],['Judy','Jude'],['Judy']),
  add('Juliana','girl',['Latin'],'youthful',58,'rising',4,['latin','elegant','classic'],['Julia','Julianne'],['Juli','Ana']),
  add('Juliette','girl',['French'],'youthful',52,'rising',3,['french','romantic','elegant'],['Juliet','Julie'],['Jules']),
  add('Kaia','girl',['Hawaiian','Greek'],'sea, earth',62,'rising',3,['hawaiian','greek','modern'],['Kaia','Maia'],['Kai']),
  add('Kalani','girl',['Hawaiian'],'the heavens',105,'rising',3,['hawaiian','celestial'],['Kalani','Alani'],[]),
  add('Karma','girl',['Sanskrit'],'destiny, action',108,'stable',2,['sanskrit','spiritual'],['Karma','Karmi'],[]),
  add('Katalin','girl',['Hungarian'],'pure',115,'stable',3,['hungarian','classic'],['Katalina','Catalina'],['Kati']),
  add('Katarina','girl',['Slavic'],'pure',100,'rising',4,['slavic','classic'],['Katrina','Katharina'],['Kat','Kati']),
  add('Katrina','girl',['Scottish','German'],'pure',98,'stable',3,['scottish','german','classic'],['Katarina','Katherine'],['Kat','Trina']),
  add('Kezia','girl',['Hebrew'],'cassia tree',175,'rising',3,['biblical','rare','nature'],['Keziah','Cassia'],['Kezi']),
  add('Khadija','girl',['Arabic'],'trustworthy',75,'stable',3,['arabic','religious','classic'],['Khadeeja','Kadija'],[]),
  add('Kiara','girl',['Italian','Irish'],'bright, dark-haired',80,'rising',3,['italian','irish'],['Chiara','Ciara'],[]),
  add('Kirra','girl',['Australian Aboriginal'],'boomerang',108,'rising',2,['aboriginal','australian'],['Kira','Kyra'],[]),
  add('Kira','girl',['Persian','Irish'],'sun, dark one',85,'rising',2,['persian','irish'],['Kyra','Kiera'],[]),
  add('Kirstie','girl',['Scottish'],'follower of Christ',110,'stable',2,['scottish','gaelic'],['Kirsty','Kirsten'],[]),
  add('Kirsty','girl',['Scottish'],'follower of Christ',105,'stable',2,['scottish','gaelic'],['Kirstie','Kirsten'],[]),
  add('Kitty','girl',['Greek'],'pure',100,'rising',2,['greek','sweet','vintage'],['Catherine','Kit'],[]),
  add('Kylie','girl',['Aboriginal'],'boomerang',88,'stable',3,['aboriginal','modern','popular'],['Kyle','Kylee'],[]),
  add('Kyra','girl',['Greek','Persian'],'throne, sun',90,'rising',2,['greek','persian'],['Kira','Keira'],[]),
  add('Lana','girl',['Celtic','Latin'],'little rock, pretty',78,'rising',2,['celtic','elegant'],['Alana','Elena'],[]),
  add('Larissa','girl',['Greek'],'citadel',100,'rising',3,['greek','russian','elegant'],['Lara','Larisa'],[]),
  add('Laurel','girl',['Latin'],'laurel tree',82,'rising',2,['latin','nature','vintage'],['Laura','Lauren'],[]),
  add('Lavinia','girl',['Latin'],'woman of Latium',100,'rising',4,['latin','roman','vintage'],['Livia','Vinia'],['Vinnie','Lavie']),
  add('Layla','girl',['Arabic'],'night',17,'rising',3,['arabic','romantic'],['Lila','Lilah'],[]),
  add('Leandra','girl',['Greek'],'lioness',115,'rising',3,['greek','strong'],['Leandre','Sandra'],[]),
  add('Leila','girl',['Arabic','Persian'],'night, dark beauty',68,'stable',3,['arabic','persian','romantic'],['Layla','Lila'],[]),
  add('Leonora','girl',['Spanish','Italian'],'shining light',95,'rising',4,['spanish','italian','vintage'],['Eleanor','Lenore'],['Nora','Leo']),
  add('Leontine','girl',['Latin'],'lion',140,'rare',3,['latin','strong','rare'],['Leontina','Leonine'],[]),
  add('Leora','girl',['Hebrew'],'light',112,'rising',3,['hebrew','light'],['Liora','Leore'],[]),
  add('Leticia','girl',['Latin'],'joy, gladness',100,'stable',4,['latin','joyful'],['Laetitia','Letitia'],['Lettie','Letty']),
  add('Lettice','girl',['Latin'],'joy',130,'rising',2,['latin','vintage'],['Leticia','Laetitia'],['Lettie']),
  add('Lilavati','girl',['Sanskrit'],'graceful, playful',175,'rare',4,['sanskrit','rare'],['Lila','Lily'],[]),
  add('Lilith','girl',['Hebrew'],'night creature',85,'rising',2,['hebrew','mythological','dark'],['Lily','Lila'],[]),
  add('Lilou','girl',['French'],'lily',112,'rising',2,['french','flower','modern'],['Lily','Lou'],[]),
  add('Lindiwe','girl',['Zulu'],'waited for',120,'stable',3,['zulu','african'],['Linda','Lindi'],[]),
  add('Linnea','girl',['Norse'],'twinflower',98,'rising',3,['norse','flower','nordic'],['Lena','Linne'],[]),
  add('Liora','girl',['Hebrew'],'my light',108,'rising',3,['hebrew','light'],['Leora','Lior'],[]),
  add('Lisette','girl',['French'],'pledged to God',110,'rising',2,['french','elegant'],['Lisette','Lizette'],['Lise']),
  add('Livia','girl',['Latin'],'blue, envious',96,'rising',3,['latin','roman'],['Olivia','Livia'],[]),
  add('Llewella','girl',['Welsh'],'light, lioness',155,'rare',3,['welsh','rare'],['Llewellyn','Ella'],[]),
  add('Lluvia','girl',['Spanish'],'rain',120,'rising',3,['spanish','nature'],['Lluvia','Liuvia'],[]),
  add('Lola','girl',['Spanish'],'sorrows, strong woman',67,'rising',2,['spanish','vivacious'],['Dolores','Lolita'],[]),
  add('Lolita','girl',['Spanish'],'sorrows',145,'stable',3,['spanish','vintage'],['Lola','Dolores'],[]),
  add('Loreto','girl',['Italian'],'laurel grove',130,'stable',3,['italian','religious'],['Loreto','Laura'],[]),
  add('Lottie','girl',['French'],'free woman',78,'rising',2,['french','vintage','sweet'],['Charlotte','Lotte'],[]),
  add('Lourdes','girl',['French'],'place of pilgrimage',120,'stable',2,['french','religious','place'],['Lourdes','Lordes'],[]),
  add('Luella','girl',['English'],'famous elf',105,'rising',3,['english','vintage'],['Luella','Louella'],['Lou','Ella']),
  add('Lumi','girl',['Finnish'],'snow',115,'rising',2,['finnish','nature','nordic'],['Lumine','Lumia'],[]),
  add('Luminara','girl',['Latin'],'shining light',140,'rare',4,['latin','rare','celestial'],['Luminary','Luna'],[]),
  add('Lunette','girl',['French'],'little moon',125,'rare',2,['french','celestial','rare'],['Luna','Lunette'],[]),
  add('Lyra','girl',['Greek'],'lyre constellation',72,'rising',2,['greek','celestial','musical'],['Lyric','Lyre'],[]),
  add('Lysandra','girl',['Greek'],'liberator of men',120,'rare',3,['greek','strong','rare'],['Lysander','Sandra'],[]),
  add('Madeleine','girl',['Hebrew','French'],'woman from Magdala',55,'rising',4,['french','biblical','elegant'],['Madeline','Madelyn'],['Maddie','Lena']),
  add('Madeline','girl',['Hebrew'],'woman from Magdala',48,'stable',3,['hebrew','popular'],['Madeleine','Madelyn'],['Maddie']),
  add('Madelyn','girl',['Hebrew'],'woman from Magdala',44,'stable',3,['hebrew','modern'],['Madeline','Madeleine'],['Maddie']),
  add('Maeve','girl',['Irish'],'she who intoxicates',39,'rising',2,['irish','mythological'],['Mae','Mavis'],[]),
  add('Magdalena','girl',['Hebrew'],'woman from Magdala',96,'rising',4,['hebrew','religious','elegant'],['Magdalene','Lena'],['Lena','Magda']),
  add('Magnolia','girl',['Latin'],'magnolia flower',85,'rising',4,['nature','flower','southern'],['Maggie','Nolia'],['Maggie','Nolia']),
  add('Mahina','girl',['Hawaiian'],'moon',118,'rising',3,['hawaiian','celestial'],['Mahina','Malina'],[]),
  add('Maika','girl',['Hawaiian','Hebrew'],'who is like God',120,'rising',3,['hawaiian','hebrew'],['Maia','Malika'],[]),
  add('Maisie','girl',['Scottish'],'pearl',62,'rising',3,['scottish','vintage','sweet'],['Daisy','Mazie'],['Maise']),
  add('Malika','girl',['Arabic'],'queen',100,'rising',3,['arabic','royal'],['Malika','Malikah'],[]),
  add('Manon','girl',['French'],'sea of bitterness',96,'rising',2,['french','elegant'],['Marion','Manon'],[]),
  add('Marceline','girl',['French','Latin'],'of Mars',108,'rising',3,['french','vintage'],['Marcella','Celine'],['Marcy']),
  add('Marcella','girl',['Latin'],'of Mars',100,'rising',3,['latin','roman','vintage'],['Marcelle','Marcy'],['Marcy','Cella']),
  add('Margaux','girl',['French'],'pearl',68,'rising',2,['french','chic','elegant'],['Margot','Margaret'],[]),
  add('Marguerite','girl',['French'],'pearl, daisy',95,'rising',3,['french','flower','vintage'],['Margaret','Margot'],['Margot']),
  add('Marianna','girl',['Hebrew','Latin'],'grace + sea',88,'rising',4,['biblical','romantic'],['Mariana','Marianne'],['Mari','Anna']),
  add('Marianne','girl',['French'],'grace + sea',90,'stable',3,['french','classic'],['Marian','Marianna'],['Mari','Anne']),
  add('Maribel','girl',['Spanish'],'beautiful Mary',102,'stable',3,['spanish','beautiful'],['Maribella','Mirabelle'],['Mari','Belle']),
  add('Marigold','girl',['English'],'golden flower',95,'rising',3,['english','flower','vintage'],['Margot','Goldie'],['Goldie']),
  add('Marilyn','girl',['Hebrew'],'sea of bitterness',110,'stable',3,['hebrew','vintage'],['Mary','Lynn'],['Lynn']),
  add('Marjolaine','girl',['French'],'marjoram herb',155,'rare',3,['french','herb','rare'],['Marjoram','Marjorie'],[]),
  add('Marjorie','girl',['French'],'pearl',108,'rising',3,['french','vintage','classic'],['Margot','Marjolaine'],['Marj','Marge']),
  add('Marlena','girl',['German'],'from Magdala',99,'rising',3,['german','vintage'],['Marlene','Lena'],['Lena']),
  add('Marlene','girl',['German'],'from Magdala',98,'stable',2,['german','vintage'],['Marlena','Lena'],['Marlena','Lena']),
  add('Martha','girl',['Aramaic'],'lady, mistress',97,'rising',2,['aramaic','biblical','vintage'],['Marta','Marthe'],['Marty','Mattie']),
  add('Mathilda','girl',['Germanic'],'mighty in battle',90,'rising',3,['germanic','vintage'],['Matilda','Tilda'],['Tilly','Tillie']),
  add('Matilda','girl',['Germanic'],'mighty in battle',62,'rising',3,['germanic','royal','vintage'],['Mathilda','Tilly'],['Tillie','Tilly']),
  add('Maxine','girl',['Latin'],'greatest',100,'rising',2,['latin','strong','vintage'],['Max','Maxie'],['Maxie']),
  add('Meadow','girl',['English'],'meadow',95,'rising',2,['nature','english','modern'],['Meadow','Willow'],[]),
  add('Meredith','girl',['Welsh'],'great ruler',100,'stable',3,['welsh','vintage'],['Merideth','Morgan'],['Meri']),
  add('Meryl','girl',['Celtic'],'bright sea',125,'stable',2,['celtic','vintage'],['Merle','Meryl','Muriel'],[]),
  add('Mia','girl',['Scandinavian'],'mine, beloved',8,'stable',2,['short','popular'],['Maya','Mya'],[]),
  add('Mikaela','girl',['Hebrew'],'who is like God',88,'rising',3,['hebrew','modern'],['Michaela','Mikayla'],['Mika']),
  add('Mikael','girl',['Hebrew'],'who is like God',115,'rising',3,['hebrew','scandinavian'],['Michaela','Mikaela'],['Mika']),
  add('Milly','girl',['Germanic'],'gentle strength',66,'rising',2,['germanic','vintage','sweet'],['Millie','Amelia'],[]),
  add('Minerva','girl',['Latin'],'goddess of wisdom',108,'rising',3,['roman','goddess','intellectual'],['Athena','Minnie'],['Minnie']),
  add('Minnie','girl',['Germanic','Hebrew'],'beloved, of the mind',96,'rising',2,['germanic','sweet','vintage'],['Minerva','Wilhelmina','Mary'],[]),
  add('Mirabelle','girl',['French','Latin'],'wonderful beauty',88,'rising',3,['french','elegant','beautiful'],['Mirabel','Mira'],['Mira','Belle']),
  add('Miriam','girl',['Hebrew'],'sea of bitterness',79,'rising',3,['biblical','classic','vintage'],['Mary','Maria'],['Miri']),
  add('Moira','girl',['Irish'],'great, destiny',105,'rising',2,['irish','mythological'],['Maura','Moire'],[]),
  add('Morag','girl',['Scottish','Irish'],'great sun',118,'stable',2,['scottish','gaelic'],['Moira','Mora'],[]),
  add('Morwenna','girl',['Welsh'],'maiden',115,'rising',3,['welsh','vintage'],['Morwen','Morgan'],[]),
  add('Muireann','girl',['Irish'],'sea-white',130,'rising',3,['irish','gaelic'],['Muireen','Muirin'],[]),
  add('Muriel','girl',['Celtic'],'bright sea',118,'rising',3,['celtic','vintage'],['Meryl','Murielle'],[]),
  add('Nadia','girl',['Slavic','Arabic'],'hope',72,'stable',3,['slavic','arabic','modern'],['Nadya','Nadine'],['Nads']),
  add('Nadine','girl',['French','Slavic'],'hope',95,'stable',2,['french','slavic','elegant'],['Nadia','Nadene'],[]),
  add('Nanette','girl',['French'],'grace',130,'stable',2,['french','vintage'],['Nannette','Annette'],['Nan','Nettie']),
  add('Nathalie','girl',['Latin'],'Christmas Day',90,'stable',3,['french','latin'],['Natalie','Natalia'],['Nat']),
  add('Nayeli','girl',['Zapotec'],'I love you',105,'rising',3,['zapotec','modern'],['Nayeli','Nayely'],[]),
  add('Nerissa','girl',['Greek'],'sea nymph',110,'rising',3,['greek','literary'],['Nessie','Nerys'],[]),
  add('Nerys','girl',['Welsh'],'lord',112,'rising',2,['welsh','gaelic'],['Nerissa','Cerys'],[]),
  add('Nessa','girl',['Irish'],'not gentle',112,'rising',2,['irish','vintage'],['Vanessa','Nessie'],[]),
  add('Nevaeh','girl',['American'],'heaven backwards',68,'stable',3,['american','modern','religious'],['Heaven','Naeva'],[]),
  add('Neve','girl',['Irish','Latin'],'snow, bright',90,'rising',2,['irish','latin','modern'],['Niamh','Neve'],[]),
  add('Niamh','girl',['Irish'],'bright',75,'rising',2,['irish','gaelic','bright'],['Neve','Niamh'],[]),
  add('Nicola','girl',['Greek'],'victorious people',92,'stable',3,['greek','italian','classic'],['Nicole','Nicolette'],['Nikki','Nico']),
  add('Nicolette','girl',['French'],'victorious people',99,'stable',3,['french','elegant'],['Nicole','Nicola'],['Nikki','Nicky']),
  add('Nina','girl',['Spanish','Hebrew'],'little girl, grace',76,'stable',2,['spanish','hebrew','classic'],['Nino','Ninette'],[]),
  add('Niobe','girl',['Greek'],'fern',145,'rare',2,['greek','mythological','rare'],['Niobe','Naiobe'],[]),
  add('Nola','girl',['Irish'],'famous',95,'rising',2,['irish','modern'],['Nola','Noleen'],[]),
  add('Noreen','girl',['Irish'],'honour',115,'stable',2,['irish','gaelic','vintage'],['Norene','Nora'],[]),
  add('Norma','girl',['Latin'],'rule, pattern',115,'stable',2,['latin','vintage'],['Nora','Norma'],[]),
  add('Nuala','girl',['Irish'],'fair-shouldered',108,'rising',3,['irish','gaelic'],['Fionnuala','Nula'],[]),
  add('Nyx','girl',['Greek'],'night goddess',108,'rising',1,['greek','goddess','celestial'],['Nix','Nyxia'],[]),
  add('Odessa','girl',['Greek'],'long journey',100,'rising',3,['greek','place','vintage'],['Odyssey','Dessa'],[]),
  add('Odette','girl',['French','Germanic'],'wealth, fortune',95,'rising',2,['french','elegant','vintage'],['Odile','Odetta'],[]),
  add('Olga','girl',['Norse','Russian'],'holy',110,'stable',2,['norse','russian','vintage'],['Helga','Oliva'],[]),
  add('Ondine','girl',['Latin'],'wave, water spirit',130,'rare',2,['latin','water','rare'],['Ondina','Undine'],[]),
  add('Opal','girl',['Sanskrit'],'jewel',92,'rising',2,['gemstone','nature','vintage'],['Opal','Opale'],[]),
  add('Oriana','girl',['Latin'],'golden dawn',105,'rising',4,['latin','celestial'],['Ariana','Oriane'],[]),
  add('Orla','girl',['Irish'],'golden princess',88,'rising',2,['irish','golden','gaelic'],['Orlaith','Aurelia'],[]),
  add('Ottilie','girl',['Germanic'],'fortune, prosperity',115,'rising',3,['germanic','vintage','elegant'],['Ottilia','Ottie'],['Ottie']),
  add('Paloma','girl',['Spanish'],'dove',92,'rising',3,['spanish','nature','peaceful'],['Paloma','Pomona'],[]),
  add('Pandora','girl',['Greek'],'all gifts',108,'rising',3,['greek','mythological'],['Sandra','Pandorae'],[]),
  add('Patience','girl',['English'],'patience',105,'stable',3,['virtue','english','vintage'],['Patience','Grace'],[]),
  add('Patricia','girl',['Latin'],'noblewoman',90,'stable',4,['latin','classic','royal'],['Pat','Tricia','Trish'],['Pat','Patsy','Trish']),
  add('Pearl','girl',['English'],'pearl gemstone',80,'rising',1,['jewel','nature','vintage'],['Perla','Pearl'],[]),
  add('Penelope','girl',['Greek'],'weaver',14,'rising',4,['greek','vintage'],['Penny','Nell'],['Penny','Nellie']),
  add('Perla','girl',['Spanish'],'pearl',105,'stable',2,['spanish','jewel'],['Pearl','Perle'],[]),
  add('Persephone','girl',['Greek'],'bringer of death, spring',100,'rising',4,['greek','goddess','mythological'],['Persephonia','Seffy'],['Seffy','Percy']),
  add('Petra','girl',['Greek','Latin'],'rock',105,'rising',2,['greek','latin','vintage'],['Peter','Petrina'],[]),
  add('Petronella','girl',['Latin'],'little stone',145,'rare',4,['latin','vintage','rare'],['Petra','Nella'],['Nella']),
  add('Philippa','girl',['Greek'],'lover of horses',98,'rising',3,['greek','royal','vintage'],['Philipa','Pippa'],['Pippa','Phil']),
  add('Phoibe','girl',['Greek'],'bright, pure',110,'rising',2,['greek','mythological'],['Phoebe','Phoibe'],[]),
  add('Pia','girl',['Latin','Italian'],'pious, devout',105,'rising',2,['latin','italian'],['Pia','Mia'],[]),
  add('Pietra','girl',['Italian'],'rock',120,'rising',3,['italian','strong'],['Petra','Pietra'],[]),
  add('Pixie','girl',['English'],'fairy creature',115,'rising',2,['english','magical','sweet'],['Pixie','Trixie'],[]),
  add('Polly','girl',['Hebrew'],'sea of bitterness',96,'rising',2,['hebrew','vintage','sweet'],['Mary','Molly','Poll'],[]),
  add('Portia','girl',['Latin'],'pig, doorway',110,'rising',2,['latin','literary'],['Portia','Porsche'],[]),
  add('Primrose','girl',['English'],'first rose',100,'rising',3,['english','flower','vintage'],['Rose','Prima'],['Prim']),
  add('Priscilla','girl',['Latin'],'ancient',96,'stable',3,['latin','biblical','vintage'],['Prissy','Cilla'],['Cilla','Prissy']),
  add('Prudence','girl',['Latin'],'prudent, wise',120,'rising',3,['latin','virtue','vintage'],['Prue','Prudie'],['Prue']),
  add('Rahel','girl',['Hebrew'],'female sheep',140,'stable',2,['hebrew','biblical'],['Rachel','Rahela'],[]),
  add('Raina','girl',['Slavic','Latin'],'queen',98,'rising',2,['slavic','latin','regal'],['Rayna','Regina'],[]),
  add('Ramona','girl',['Spanish','Germanic'],'wise protector',105,'rising',3,['spanish','vintage'],['Ramone','Remon'],['Mona']),
  add('Raphaela','girl',['Hebrew'],'God has healed',115,'rising',4,['hebrew','religious'],['Rafaela','Raphael'],['Rafi']),
  add('Raquel','girl',['Spanish'],'female sheep',100,'stable',2,['spanish','biblical'],['Rachel','Raquelle'],[]),
  add('Raven','girl',['English'],'black bird',80,'stable',2,['nature','bird','gothic'],['Ravenna','Robin'],[]),
  add('Ravenna','girl',['Italian'],'raven, place in Italy',100,'rising',3,['italian','place','elegant'],['Raven','Raven'],[]),
  add('Rebekah','girl',['Hebrew'],'to bind',78,'rising',3,['biblical','vintage'],['Rebecca','Becca'],['Becca','Becky']),
  add('Regina','girl',['Latin'],'queen',106,'stable',3,['latin','royal','vintage'],['Raina','Reggie'],['Reggie']),
  add('Renata','girl',['Latin'],'reborn',108,'rising',3,['latin','elegant','italian'],['Renate','Rena'],['Rena']),
  add('Renee','girl',['French'],'reborn',100,'stable',2,['french','classic'],['Renata','Renne'],[]),
  add('Rhiannon','girl',['Welsh'],'divine queen',108,'rising',3,['welsh','mythological'],['Rhianna','Rihanna'],['Rhi']),
  add('Rin','girl',['Japanese'],'dignified, cold',120,'rising',1,['japanese','short'],['Rin','Rima'],[]),
  add('Riona','girl',['Irish'],'queen, sainted',115,'rising',3,['irish','gaelic','regal'],['Rionna','Rion'],[]),
  add('Romilda','girl',['Germanic'],'famous battle',165,'rare',3,['germanic','vintage','rare'],['Romilde','Roma'],[]),
  add('Romilly','girl',['Latin','French'],'from Rome',100,'rising',3,['latin','place','elegant'],['Romilly','Romy'],['Romy']),
  add('Romy','girl',['German','Latin'],'from Rome, rosemary',92,'rising',2,['german','elegant','short'],['Romilly','Rosemary'],[]),
  add('Rosalba','girl',['Italian'],'white rose',120,'rising',3,['italian','flower'],['Rosa','Alba'],[]),
  add('Rosalee','girl',['English'],'rose',88,'rising',3,['english','flower'],['Rosalie','Rosa'],[]),
  add('Rosalind','girl',['Germanic'],'gentle horse, tender rose',92,'rising',3,['germanic','literary','vintage'],['Rosaline','Rosalynn'],['Ros','Roz','Linda']),
  add('Rosaline','girl',['Germanic','Latin'],'gentle rose',98,'rising',3,['germanic','literary'],['Rosalind','Rosa'],['Ros']),
  add('Rosalynn','girl',['Germanic'],'gentle rose',105,'stable',3,['germanic','american'],['Rosalind','Lynn'],['Ros','Lynn']),
  add('Rosamund','girl',['Germanic'],'horse protection, rose of the world',108,'rising',3,['germanic','vintage'],['Rosalind','Rosamond'],['Ros','Rosie']),
  add('Rosemary','girl',['Latin','English'],'dew of the sea, herb',98,'rising',3,['herb','nature','vintage'],['Rose','Mary'],['Rose','Rosie']),
  add('Rowena','girl',['Germanic','Welsh'],'famous friend',105,'rising',3,['germanic','literary'],['Rona','Rowena'],[]),
  add('Roxana','girl',['Persian'],'bright, dawn',100,'rising',3,['persian','historical'],['Roxanne','Roxy'],['Roxy']),
  add('Roxanne','girl',['Persian'],'bright',95,'stable',2,['persian','vintage'],['Roxana','Roxy'],['Roxy']),
  add('Rue','girl',['English','French'],'herb, regret',112,'rising',1,['herb','nature','literary'],['Rose','June'],[]),
  add('Sable','girl',['French'],'black, fur',115,'rising',2,['french','colour','nature'],['Sabrina','Sable'],[]),
  add('Sabine','girl',['Latin'],'Sabine women',102,'rising',2,['latin','historical','elegant'],['Sabina','Savina'],[]),
  add('Sabrina','girl',['Latin','Celtic'],'from the River Severn',80,'stable',3,['latin','celtic','classic'],['Sabine','Brina'],['Brina']),
  add('Saffron','girl',['Arabic'],'yellow spice',100,'rising',2,['arabic','spice','colour'],['Saffie','Safron'],['Saffie']),
  add('Sahara','girl',['Arabic'],'desert',108,'rising',3,['arabic','place','nature'],['Sara','Sahara'],[]),
  add('Sakura','girl',['Japanese'],'cherry blossom',98,'rising',3,['japanese','flower','nature'],['Sakura','Yuki'],[]),
  add('Sally','girl',['Hebrew'],'princess',110,'stable',2,['hebrew','vintage'],['Sarah','Sadie','Sal'],[]),
  add('Salomé','girl',['Hebrew'],'peace',108,'rising',3,['hebrew','biblical'],['Salome','Shalom'],[]),
  add('Samara','girl',['Hebrew','Arabic'],'guardian, night',80,'rising',3,['hebrew','arabic','modern'],['Samira','Samantha'],['Sam']),
  add('Samira','girl',['Arabic'],'entertainer',85,'rising',3,['arabic','modern'],['Samara','Amira'],['Sam']),
  add('Sandie','girl',['Greek'],'defending men',125,'stable',2,['greek','vintage'],['Sandra','Sandy'],[]),
  add('Sandra','girl',['Greek'],'defending men',102,'stable',2,['greek','vintage','popular'],['Sandie','Cassandra'],['Sandy','Sandie']),
  add('Sandy','girl',['Greek'],'defending men',115,'stable',2,['greek','vintage'],['Sandra','Cassandra'],[]),
  add('Santana','girl',['Spanish'],'holy, sainted',108,'stable',3,['spanish','religious'],['Santa','Santina'],[]),
  add('Saoirse','girl',['Irish'],'freedom, liberty',80,'rising',2,['irish','gaelic','freedom'],['Saoirse','Sorcha'],[]),
  add('Saskia','girl',['Dutch','Slavic'],'Saxon woman',88,'rising',2,['dutch','slavic','elegant'],['Sas','Kia'],[]),
  add('Séraphine','girl',['French','Hebrew'],'burning one, angel',105,'rising',3,['french','religious'],['Seraphina','Sera'],['Sera']),
  add('Seraphina','girl',['Hebrew'],'burning one, angel',88,'rising',4,['hebrew','religious','elegant'],['Séraphine','Sera'],['Sera','Fina']),
  add('Serena','girl',['Latin'],'calm, serene',84,'rising',3,['latin','peaceful'],['Selena','Sienna'],['Rena']),
  add('Sharon','girl',['Hebrew'],'plain, flat area',110,'stable',2,['biblical','vintage'],['Sharron','Sherry'],[]),
  add('Sheba','girl',['Hebrew'],'from Sheba',130,'rising',2,['biblical','vintage'],['Bathsheba','Sheba'],[]),
  add('Sheila','girl',['Irish'],'heavenly',105,'stable',2,['irish','classic'],['Sheela','Shela'],[]),
  add('Sibyl','girl',['Greek'],'prophetess',135,'rising',2,['greek','vintage'],['Sybil','Sibella'],[]),
  add('Sigrid','girl',['Norse'],'victory secret',120,'rising',2,['norse','nordic'],['Siri','Sigrit'],[]),
  add('Silvana','girl',['Latin'],'forest, woods',115,'rising',3,['latin','nature'],['Sylvana','Silvia'],[]),
  add('Silvia','girl',['Latin'],'forest, woods',100,'stable',3,['latin','nature','classic'],['Sylvia','Sylvie'],['Sylvie']),
  add('Siobhan','girl',['Irish'],'God is gracious',88,'rising',2,['irish','gaelic'],['Shivon','Shivonne'],[]),
  add('Siri','girl',['Norse'],'victory, secret',98,'rising',2,['norse','short','modern'],['Sigrid','Siri'],[]),
  add('Solange','girl',['French'],'solemn, annual',125,'rising',2,['french','rare','saint'],['Solanna','Sole'],[]),
  add('Soleil','girl',['French'],'sun',100,'rising',2,['french','celestial','nature'],['Soleil','Solange'],[]),
  add('Solveig','girl',['Norse'],'sun strength',115,'rising',2,['norse','nordic'],['Solvig','Sol'],[]),
  add('Sonia','girl',['Slavic'],'wisdom',99,'stable',3,['slavic','classic'],['Sonja','Sonya'],[]),
  add('Sorcha','girl',['Irish'],'bright, radiant',98,'rising',2,['irish','gaelic'],['Saoirse','Sorsha'],[]),
  add('Starla','girl',['American'],'star',120,'stable',2,['american','celestial','modern'],['Starling','Stella'],[]),
  add('Stefania','girl',['Italian'],'crown',106,'stable',4,['italian','classic'],['Stephanie','Stefanie'],[]),
  add('Svetlana','girl',['Slavic'],'light',105,'stable',3,['slavic','elegant','light'],['Sveta','Lana'],[]),
  add('Sybil','girl',['Greek'],'prophetess',140,'rising',2,['greek','vintage','literary'],['Sibyl','Cybil'],[]),
  add('Sylvie','girl',['French','Latin'],'forest',88,'rising',2,['french','nature','elegant'],['Sylvia','Silvia'],[]),
  add('Tamsin','girl',['English'],'twin',96,'rising',2,['english','cornish'],['Tamzin','Tamasin'],['Tam']),
  add('Tansy','girl',['Greek'],'immortality herb',100,'rising',2,['greek','herb','nature'],['Daisy','Pansy'],[]),
  add('Tanya','girl',['Slavic'],'fairy queen',102,'stable',2,['slavic','classic'],['Tatyana','Tania'],[]),
  add('Taryn','girl',['Welsh','Irish'],'thunder',110,'stable',2,['welsh','modern'],['Tara','Erin'],[]),
  add('Tatiana','girl',['Slavic','Latin'],'fairy queen',92,'rising',4,['slavic','elegant'],['Tanya','Tatyana'],['Tati','Tanya']),
  add('Tempest','girl',['English'],'stormy, tempestuous',115,'rising',2,['english','nature','bold'],['Storm','Tempesta'],[]),
  add('Teresa','girl',['Spanish','Greek'],'harvester',88,'stable',3,['spanish','religious','classic'],['Theresa','Terese'],['Tess','Terry']),
  add('Terpsichore','girl',['Greek'],'delight in dancing',210,'rare',4,['greek','muse','rare'],['Terp','Cora'],[]),
  add('Terri','girl',['Germanic'],'ruler of the people',115,'stable',2,['germanic','vintage'],['Teresa','Terry'],[]),
  add('Thalassa','girl',['Greek'],'sea',135,'rare',3,['greek','nature','water'],['Thalia','Thallia'],[]),
  add('Thalia','girl',['Greek'],'to flourish, muse',95,'rising',3,['greek','muse','mythological'],['Talia','Thalia'],[]),
  add('Theodora','girl',['Greek'],'gift of God',87,'rising',4,['greek','royal','vintage'],['Thea','Dorothy'],['Thea','Teddy','Dora']),
  add('Tilda','girl',['Germanic'],'battle mighty',85,'rising',2,['germanic','vintage','short'],['Matilda','Hilda'],['Tillie']),
  add('Tillie','girl',['Germanic'],'battle mighty',92,'rising',3,['germanic','sweet','vintage'],['Matilda','Tilda'],[]),
  add('Tilly','girl',['Germanic'],'battle mighty',78,'rising',2,['germanic','sweet','popular'],['Matilda','Tillie'],[]),
  add('Trixie','girl',['Latin'],'bringer of joy',108,'rising',2,['latin','playful','vintage'],['Beatrix','Beatrice'],[]),
  add('Trudy','girl',['Germanic'],'spear of strength',118,'rising',2,['germanic','vintage'],['Gertrude','Trudie'],[]),
  add('Ulrica','girl',['Germanic'],'power of the wolf',155,'rare',3,['germanic','strong','rare'],['Ulrika','Frederica'],[]),
  add('Uma','girl',['Sanskrit'],'nation, tranquility',108,'rising',2,['sanskrit','modern'],['Oma','Uma'],[]),
  add('Una','girl',['Irish','Latin'],'one, lamb',108,'rising',2,['irish','latin','vintage'],['Oona','Oonagh'],[]),
  add('Undine','girl',['Latin'],'wave, water spirit',135,'rising',2,['latin','water','mythological'],['Ondine','Ondina'],[]),
  add('Ursula','girl',['Latin'],'little female bear',115,'rising',3,['latin','saint','vintage'],['Ursa','Orsula'],['Ursie']),
  add('Valentina','girl',['Latin'],'strong, healthy',62,'rising',4,['latin','romantic'],['Valentine','Val'],['Val','Tina']),
  add('Valerie','girl',['Latin'],'strong, healthy',80,'stable',3,['latin','classic'],['Valeria','Valentina'],['Val']),
  add('Vashti','girl',['Persian'],'beautiful',145,'rare',2,['persian','biblical','rare'],['Vasht','Asti'],[]),
  add('Venetia','girl',['Latin'],'from Venice',130,'rare',4,['latin','place','elegant'],['Venice','Venetia'],[]),
  add('Venice','girl',['Italian'],'place name',120,'rising',2,['italian','place','elegant'],['Venetia','Veronica'],[]),
  add('Vesta','girl',['Latin'],'goddess of the hearth',115,'rising',2,['roman','goddess'],['Hestia','Vesta'],[]),
  add('Vianna','girl',['Latin'],'life',115,'rising',3,['latin','modern'],['Vienna','Viviana'],[]),
  add('Vienna','girl',['Latin'],'place name',108,'rising',3,['latin','place','elegant'],['Vianna','Vivienne'],[]),
  add('Vigdis','girl',['Norse'],'war goddess',175,'rare',2,['norse','rare','warrior'],['Vigdis','Dis'],[]),
  add('Viola','girl',['Latin'],'violet',88,'rising',3,['latin','musical','literary'],['Violet','Violette'],[]),
  add('Viveca','girl',['Scandinavian'],'alive',115,'rising',3,['scandinavian','elegant'],['Vivian','Viveka'],[]),
  add('Vivian','girl',['Latin'],'alive',82,'rising',3,['latin','elegant','vintage'],['Vivienne','Viviana'],['Viv']),
  add('Walburga','girl',['Germanic'],'protecting ruler',200,'rare',3,['germanic','saint','rare'],['Walpurga','Walburga'],[]),
  add('Wanda','girl',['Slavic'],'wanderer',115,'stable',2,['slavic','classic'],['Wanda','Wendy'],[]),
  add('Wendy','girl',['English'],'friend',96,'stable',2,['english','literary','vintage'],['Gwendolyn','Wren'],[]),
  add('Wilhelmina','girl',['Germanic'],'resolute protector',115,'rising',4,['germanic','vintage','royal'],['Mina','Wilhelmine'],['Mina','Billie','Minnie']),
  add('Willa','girl',['Germanic'],'resolute protector',78,'rising',2,['germanic','modern'],['Billie','Wilhelmina'],[]),
  add('Willow','girl',['English'],'willow tree',32,'rising',2,['nature','tree','modern'],['Willa','Billow'],[]),
  add('Winona','girl',['Native American'],'firstborn daughter',110,'rising',3,['native american','vintage'],['Wenona','Nona'],[]),
  add('Wren','girl',['English'],'small bird',67,'rising',1,['nature','bird','modern'],['Ren','Robin'],[]),
  add('Xena','girl',['Greek'],'guest, stranger',110,'rising',2,['greek','strong','modern'],['Xena','Zena'],[]),
  add('Xiomara','girl',['Spanish','Germanic'],'battle ready',105,'rising',4,['spanish','strong'],['Xiomara','Zamora'],[]),
  add('Ximena','girl',['Spanish'],'hearkening',100,'rising',3,['spanish','modern'],['Jimena','Ximena'],[]),
  add('Xylia','girl',['Greek'],'forest dweller',140,'rare',3,['greek','nature','rare'],['Sylvia','Xylia'],[]),
  add('Yara','girl',['Arabic','Brazilian'],'small butterfly',105,'rising',2,['arabic','brazilian','modern'],['Yara','Sara'],[]),
  add('Yemisi','girl',['Yoruba'],'surrounded by wealth',130,'stable',3,['yoruba','african'],['Yemi','Yemisi'],[]),
  add('Yenna','girl',['Scottish'],'God is gracious',145,'rare',2,['scottish','rare'],['Jenna','Enna'],[]),
  add('Yolanda','girl',['Greek','Spanish'],'violet flower',105,'stable',3,['greek','spanish','vintage'],['Yolande','Iolanthe'],['Yoli']),
  add('Yuki','girl',['Japanese'],'snow, happiness',100,'rising',2,['japanese','nature'],['Yuko','Yuki'],[]),
  add('Yuna','girl',['Japanese'],'gentle, affectionate',105,'rising',2,['japanese','soft'],['Luna','Yuna'],[]),
  add('Zahra','girl',['Arabic'],'flower, shining',88,'rising',2,['arabic','flower','elegant'],['Zara','Zahrah'],[]),
  add('Zanele','girl',['Zulu'],'they are enough',120,'stable',3,['zulu','african'],['Zandi','Zanele'],[]),
  add('Zara','girl',['Arabic','Hebrew'],'princess, radiance',48,'rising',2,['arabic','modern'],['Sara','Zahra'],[]),
  add('Zelda','girl',['Germanic'],'grey battle maid',88,'rising',2,['germanic','vintage','literary'],['Griselda','Zelda'],[]),
  add('Zelia','girl',['Greek'],'zealous',120,'rare',3,['greek','rare'],['Zeal','Zele'],[]),
  add('Zenobia','girl',['Greek'],'life of Zeus',130,'rare',4,['greek','historical','regal'],['Zena','Nobia'],[]),
  add('Zephyrine','girl',['Greek'],'west wind',155,'rare',3,['greek','nature','rare'],['Zephyr','Seraphine'],[]),
  add('Zola','girl',['African','Italian'],'earth, tranquil',95,'rising',2,['african','italian','modern'],['Zola','Lola'],[]),
].filter(Boolean);

const all = [...existing, ...more];
writeFileSync('src/data/baby-names.json', JSON.stringify(all, null, 2), 'utf8');
console.log(`✅ Total names: ${all.length} (added ${more.length})`);
