import { readFileSync, writeFileSync } from 'fs';

const existing = JSON.parse(readFileSync('src/data/baby-names.json', 'utf8'));
let nextId = existing.length + 1;

const n = (name, gender, origin, meaning, rank, trend, syllables, tags, related, nicknames) => ({
  id: String(nextId++),
  name, gender, origin, meaning,
  popularityRank: rank,
  popularityTrend: trend,
  syllables,
  startingLetter: name[0],
  tags, relatedNames: related, nicknames,
});

const newNames = [
  // ── GIRLS ───────────────────────────────────────────────────────────────────
  n('Abigail','girl',['Hebrew'],'father is joyful',16,'stable',4,['biblical','classic','popular'],['Abbey','Abby','Gail'],['Abby','Abbey']),
  n('Adelaide','girl',['Germanic'],'noble, nobility',45,'rising',4,['vintage','elegant','royal'],['Adeline','Adele','Alice'],['Addie','Ada']),
  n('Adeline','girl',['French','Germanic'],'noble, nobility',50,'rising',4,['vintage','french','elegant'],['Adelaide','Adele','Adaline'],['Addie']),
  n('Adriana','girl',['Latin'],'from Hadria',88,'stable',4,['romantic','latin','classic'],['Adrienne','Ariana','Diana'],['Adri']),
  n('Agnes','girl',['Greek','Latin'],'pure, holy',200,'rising',2,['vintage','saint','classic'],['Agatha','Ines','Inez'],['Aggie']),
  n('Aileen','girl',['Irish','Scottish'],'bright, shining light',180,'stable',3,['irish','classic','light'],['Eileen','Elaine','Irene'],['Ali']),
  n('Ainsley','girl',['Scottish'],'one\'s own meadow',95,'rising',3,['scottish','modern','nature'],['Ashley','Ansley','Presley'],[]),
  n('Alana','girl',['Irish','Hawaiian'],'precious, awakening',70,'stable',3,['irish','hawaiian','modern'],['Alana','Elena','Lana'],['Lana']),
  n('Alexa','girl',['Greek'],'defender of mankind',55,'stable',3,['modern','greek','strong'],['Alexandra','Alexis','Alex'],['Alex']),
  n('Alexandra','girl',['Greek'],'defender of mankind',30,'stable',5,['classic','royal','strong'],['Alexa','Alexis','Sandra'],['Alex','Sandra','Lexie']),
  n('Alice','girl',['Germanic','French'],'noble, of nobility',22,'rising',2,['classic','literary','vintage'],['Adelaide','Alicia','Alison'],['Ali','Allie']),
  n('Alicia','girl',['Spanish','Germanic'],'noble',60,'stable',4,['spanish','classic','elegant'],['Alice','Alisha','Alissa'],['Ali']),
  n('Alina','girl',['Slavic','Arabic'],'bright, beautiful',65,'rising',3,['slavic','elegant','modern'],['Alena','Elena','Lina'],['Ali']),
  n('Allison','girl',['Germanic','French'],'noble',40,'stable',3,['classic','popular','strong'],['Alice','Alison','Alyson'],['Allie']),
  n('Alyssa','girl',['Greek'],'rational',35,'stable',3,['greek','popular','modern'],['Melissa','Alissa','Elyssa'],['Lyssa']),
  n('Amanda','girl',['Latin'],'worthy of love',75,'stable',3,['classic','latin','popular'],['Miranda','Samantha','Amy'],['Mandy','Amy']),
  n('Amber','girl',['Arabic','English'],'jewel, amber stone',85,'stable',2,['nature','jewel','classic'],['Ambre','Ember','Scarlett'],[]),
  n('Amelie','girl',['French'],'hardworking',42,'rising',3,['french','vintage','elegant'],['Amelia','Emily','Emilie'],['Amy','Millie']),
  n('Amy','girl',['French','Latin'],'beloved',80,'stable',2,['classic','short','popular'],['Amelia','Aimee','Emma'],['Aims']),
  n('Ana','girl',['Spanish','Portuguese'],'grace',90,'stable',2,['spanish','biblical','classic'],['Anna','Hannah','Anita'],[]),
  n('Anastasia','girl',['Greek'],'resurrection',100,'rising',5,['greek','royal','elegant'],['Stacy','Ana','Tasia'],['Stacy','Nastia','Ana']),
  n('Andrea','girl',['Greek'],'strong, manly',95,'stable',3,['classic','greek','strong'],['Andria','Angela','Adriana'],['Andie','Andy']),
  n('Angela','girl',['Greek','Latin'],'messenger of God',110,'stable',3,['classic','religious','popular'],['Angel','Angelica','Angelina'],['Angie']),
  n('Angelica','girl',['Latin'],'angelic',115,'stable',4,['romantic','religious','elegant'],['Angela','Angelina','Angel'],['Angie']),
  n('Anita','girl',['Spanish'],'grace',130,'stable',3,['spanish','classic','popular'],['Ana','Anna','Nancy'],[]),
  n('Annabelle','girl',['French','Hebrew'],'grace and beauty',48,'rising',3,['romantic','vintage','popular'],['Anna','Belle','Arabella'],['Anna','Belle','Annie']),
  n('Anne','girl',['Hebrew','French'],'grace',120,'stable',1,['classic','royal','biblical'],['Anna','Annie','Ann'],['Annie']),
  n('Annette','girl',['French'],'grace',150,'stable',2,['french','vintage','classic'],['Anne','Anna','Antoinette'],['Annie','Nettie']),
  n('Arabella','girl',['Latin'],'yielding to prayer',60,'rising',4,['elegant','vintage','romantic'],['Isabella','Arabella','Bella'],['Bella','Ara','Belle']),
  n('Ariana','girl',['Italian','Welsh'],'holy',32,'rising',4,['modern','popular','musical'],['Aria','Ariel','Diana'],['Ari','Ana']),
  n('Ariel','girl',['Hebrew'],'lion of God',75,'stable',3,['biblical','literary','modern'],['Arielle','Aria','Arial'],[]),
  n('Ariella','girl',['Hebrew'],'lion of God',85,'rising',4,['biblical','elegant','modern'],['Ariel','Aria','Gabriella'],['Ari','Ella']),
  n('Astrid','girl',['Norse'],'divinely beautiful',90,'rising',2,['norse','strong','vintage'],['Astrid','Ingrid','Sigrid'],[]),
  n('Athena','girl',['Greek'],'goddess of wisdom',70,'rising',3,['greek','mythological','strong'],['Diana','Hera','Phoebe'],[]),
  n('Aubrey','girl',['Germanic'],'elf ruler',38,'stable',3,['neutral','modern','popular'],['Audrey','Aubree','Autumn'],[]),
  n('Audrey','girl',['English'],'noble strength',24,'rising',3,['vintage','elegant','royal'],['Aubrey','Audrina','Audra'],['Audie']),
  n('Aurora','girl',['Latin'],'dawn',20,'rising',4,['celestial','nature','elegant'],['Aurora','Dawn','Aurelia'],['Rory','Rora']),
  n('Autumn','girl',['English'],'the fall season',55,'stable',2,['nature','season','modern'],['Summer','April','April'],[]),
  n('Ava','girl',['Latin','Hebrew'],'life',3,'stable',2,['classic','short','popular'],['Eva','Avery','Aviana'],[]),
  n('Avery','girl',['English'],'ruling with elf-wisdom',16,'rising',3,['neutral','modern','popular'],['Aubrey','Ivory','Averie'],[]),
  n('Ayla','girl',['Turkish','Hebrew'],'halo of light, oak tree',55,'rising',3,['modern','turkish','nature'],['Isla','Ella','Layla'],[]),
  n('Beatrice','girl',['Latin'],'she who brings happiness',75,'rising',3,['vintage','literary','italian'],['Beatrix','Bea','Trixie'],['Bea','Trixie']),
  n('Beatrix','girl',['Latin'],'voyager, blessed',80,'rising',3,['vintage','literary','elegant'],['Beatrice','Bea','Trixie'],['Bea','Trixie']),
  n('Bella','girl',['Italian','Spanish'],'beautiful',40,'stable',2,['italian','popular','modern'],['Isabella','Arabella','Stella'],['Bell']),
  n('Belle','girl',['French'],'beautiful',85,'stable',1,['french','literary','elegant'],['Bella','Isabel','Annabelle'],[]),
  n('Bianca','girl',['Italian'],'white, fair',90,'stable',3,['italian','elegant','literary'],['Blanca','Bianca','Giovanna'],['Bia']),
  n('Blair','girl',['Scottish'],'field, plain',90,'stable',1,['scottish','neutral','modern'],['Blake','Blaire','Clare'],[]),
  n('Blake','girl',['English'],'fair-haired',55,'rising',1,['neutral','modern','short'],['Blair','Blake','Blaike'],[]),
  n('Bonnie','girl',['Scottish'],'pretty, cheerful',120,'stable',2,['scottish','vintage','cheerful'],['Bonita','Brianna','Bethany'],[]),
  n('Brenda','girl',['Norse','Irish'],'sword, torch',140,'stable',2,['norse','classic','vintage'],['Brenna','Brendan','Brianna'],[]),
  n('Briar','girl',['English'],'thorny plant',100,'rising',2,['nature','modern','earthy'],['Brier','Rose','Violet'],[]),
  n('Brianna','girl',['Irish'],'strong, virtuous',45,'stable',3,['irish','strong','popular'],['Briana','Bryanna','Breanna'],['Bri','Bree']),
  n('Bridget','girl',['Irish'],'strength, exalted one',115,'stable',2,['irish','saint','classic'],['Brigid','Brigitte','Birdie'],['Biddy','Birdie']),
  n('Brielle','girl',['French','Hebrew'],'God is my strength',60,'rising',3,['french','modern','elegant'],['Briella','Gabrielle','Elle'],['Bri']),
  n('Brooke','girl',['English'],'small stream',65,'stable',1,['nature','modern','short'],['Brook','Brooklyn','Blake'],[]),
  n('Brooklyn','girl',['English'],'broken land',35,'stable',3,['modern','place','popular'],['Brooke','Braylee','Brittany'],['Brook','Lynnie']),
  n('Brynn','girl',['Welsh'],'hill',80,'rising',1,['welsh','short','nature'],['Bryn','Wynn','Lynn'],[]),
  n('Callie','girl',['Greek'],'beautiful',75,'stable',2,['greek','modern','cheerful'],['Callie','Calista','Calla'],['Cal']),
  n('Camille','girl',['French','Latin'],'helper to the priest',65,'stable',2,['french','elegant','classic'],['Camila','Camelia','Mille'],['Cami','Millie']),
  n('Cara','girl',['Irish','Italian'],'dear friend, beloved',110,'stable',2,['irish','italian','classic'],['Kara','Carina','Carla'],[]),
  n('Caroline','girl',['French','Germanic'],'free woman',28,'stable',4,['classic','royal','elegant'],['Carolina','Carol','Carolyn'],['Carrie','Caro','Lina']),
  n('Cassandra','girl',['Greek'],'shining upon man',100,'stable',3,['greek','mythological','classic'],['Cassie','Sandra','Cassidy'],['Cassie','Sandy']),
  n('Cassidy','girl',['Irish'],'curly-haired',80,'stable',3,['irish','modern','spirited'],['Cassandra','Cassie','Cassie'],['Cass','Cassie']),
  n('Cecilia','girl',['Latin'],'blind',85,'rising',4,['saint','musical','vintage'],['Cecile','Cecily','Celia'],['Cece','Cecy']),
  n('Celeste','girl',['Latin'],'heavenly',75,'rising',2,['celestial','elegant','french'],['Celestia','Stella','Skye'],[]),
  n('Celine','girl',['French'],'moon, heavenly',90,'rising',2,['french','elegant','musical'],['Celeste','Selene','Selena'],[]),
  n('Chloe','girl',['Greek'],'blooming, fertility',9,'stable',2,['greek','popular','nature'],['Zoe','Cleo','Chloe'],[]),
  n('Christina','girl',['Greek'],'follower of Christ',105,'stable',3,['religious','classic','popular'],['Christine','Kristina','Tina'],['Christie','Tina']),
  n('Claire','girl',['French'],'bright, clear',27,'stable',1,['french','classic','elegant'],['Clara','Clare','Clarice'],[]),
  n('Clara','girl',['Latin'],'bright, clear',31,'rising',2,['classic','vintage','elegant'],['Claire','Clarice','Clair'],[]),
  n('Claudia','girl',['Latin'],'lame',95,'stable',3,['roman','classic','vintage'],['Claudine','Claudette','Gloria'],[]),
  n('Clementine','girl',['French','Latin'],'mild, merciful',100,'rising',4,['vintage','french','fruit'],['Clement','Clemmie','Mandarin'],['Clemmie','Clem']),
  n('Cora','girl',['Greek'],'maiden',48,'rising',2,['greek','vintage','elegant'],['Coral','Coraline','Nora'],['Cori']),
  n('Corinne','girl',['Greek','French'],'maiden',120,'stable',2,['french','classic','elegant'],['Cora','Corinna','Corin'],[]),
  n('Crystal','girl',['Greek'],'earth mineral, clear',100,'stable',2,['nature','modern','sparkly'],['Krystal','Chrystal','Christal'],[]),
  n('Daisy','girl',['English'],'day\'s eye, flower',52,'rising',2,['flower','nature','vintage'],['Dahlia','Lily','Poppy'],[]),
  n('Dana','girl',['Hebrew','Irish'],'God is my judge',130,'stable',2,['hebrew','neutral','classic'],['Diana','Danielle','Donna'],[]),
  n('Daniella','girl',['Hebrew'],'God is my judge',75,'stable',4,['biblical','romantic','latin'],['Danielle','Daniela','Dani'],['Dani']),
  n('Danielle','girl',['Hebrew','French'],'God is my judge',70,'stable',3,['biblical','french','popular'],['Daniella','Daniela','Nicole'],['Dani','Elle']),
  n('Daphne','girl',['Greek'],'laurel tree',70,'rising',2,['greek','mythological','nature'],['Aphne','Delphine','Fern'],[]),
  n('Dawn','girl',['English'],'sunrise',140,'stable',1,['nature','classic','light'],['Aurora','Dawn','Skye'],[]),
  n('Deborah','girl',['Hebrew'],'bee',150,'stable',3,['biblical','vintage','classic'],['Debra','Deb','Bora'],['Debbie','Deb']),
  n('Delilah','girl',['Hebrew'],'delicate, languishing',42,'rising',3,['biblical','romantic','elegant'],['Lilah','Leila','Lila'],['Lilah','Dee']),
  n('Diana','girl',['Latin'],'divine, moon goddess',65,'stable',3,['roman','mythological','royal'],['Diane','Dina','Dianna'],['Di']),
  n('Dora','girl',['Greek'],'gift',150,'stable',2,['greek','vintage','classic'],['Dorothy','Theodora','Isadora'],['Dori']),
  n('Dorothy','girl',['Greek'],'gift of God',120,'rising',3,['vintage','literary','classic'],['Dora','Dot','Thea'],['Dot','Dottie']),
  n('Eden','girl',['Hebrew'],'pleasure, paradise',55,'rising',2,['biblical','nature','modern'],['Eva','Eve','Jade'],[]),
  n('Edith','girl',['English'],'prosperous in war',100,'rising',2,['vintage','royal','classic'],['Edna','Ethel','Maude'],['Edie']),
  n('Eleanor','girl',['French','Greek'],'bright, shining one',25,'rising',3,['royal','vintage','classic'],['Elena','Eleanora','Ellie'],['Ellie','Nell','Nora']),
  n('Elena','girl',['Greek','Spanish'],'bright, shining light',26,'rising',3,['greek','romantic','elegant'],['Eleanor','Ellen','Helena'],['Elle','Ellie','Lena']),
  n('Eliza','girl',['Hebrew'],'my God is an oath',35,'rising',3,['vintage','literary','elegant'],['Elizabeth','Elisa','Elise'],['Liza','Ellie']),
  n('Elizabeth','girl',['Hebrew'],'my God is an oath',14,'stable',4,['biblical','royal','classic'],['Eliza','Elise','Elsa'],['Ellie','Liz','Beth','Lizzy']),
  n('Ella','girl',['Germanic','Hebrew'],'all, completely',8,'stable',2,['popular','short','elegant'],['Eleanor','Ellen','Ellie'],['Ellie']),
  n('Elle','girl',['French'],'she',58,'rising',1,['french','modern','chic'],['Ella','Ellie','Elena'],[]),
  n('Ellen','girl',['Greek','English'],'bright, shining',105,'stable',2,['classic','vintage','light'],['Eleanor','Elena','Helen'],['Ellie']),
  n('Ellie','girl',['Greek','English'],'bright, shining',18,'rising',2,['popular','sweet','modern'],['Eleanor','Ella','Elena'],[]),
  n('Elsa','girl',['Hebrew','German'],'my God is an oath',75,'rising',2,['german','royal','vintage'],['Elisa','Else','Ilse'],['Els']),
  n('Emilia','girl',['Latin'],'rival, eager',22,'rising',4,['latin','romantic','classic'],['Amelia','Emily','Emelia'],['Mia','Emmy','Lia']),
  n('Emily','girl',['Latin'],'rival, eager',4,'stable',3,['classic','popular','timeless'],['Emma','Amelia','Emilia'],['Em','Emmy']),
  n('Emma','girl',['Germanic'],'whole, universal',1,'stable',2,['classic','popular','top'],['Emily','Emilia','Emmeline'],['Em']),
  n('Eva','girl',['Hebrew'],'life',50,'rising',2,['biblical','elegant','classic'],['Ava','Eve','Evie'],['Evie']),
  n('Evangeline','girl',['Greek'],'bearer of good news',65,'rising',5,['religious','romantic','elegant'],['Evie','Eva','Angelina'],['Eva','Evie','Angel']),
  n('Eve','girl',['Hebrew'],'life',85,'stable',1,['biblical','classic','short'],['Eva','Evie','Ava'],[]),
  n('Evie','girl',['Hebrew','English'],'life',45,'rising',3,['vintage','sweet','popular'],['Eve','Eva','Evelyn'],['Eve']),
  n('Faith','girl',['English'],'trust, belief',60,'stable',1,['virtue','religious','classic'],['Hope','Grace','Charity'],[]),
  n('Felicity','girl',['Latin'],'good fortune, happiness',85,'rising',4,['virtue','vintage','latin'],['Felicia','Felice','Joy'],['Flic','Lissy']),
  n('Fiona','girl',['Irish','Scottish'],'white, fair',75,'rising',3,['irish','scottish','nature'],['Finn','Fionna','Siobhan'],['Fi']),
  n('Florence','girl',['Latin'],'flourishing, prosperous',70,'rising',3,['vintage','italian','classic'],['Flora','Flossie','Florentine'],['Florrie','Flo']),
  n('Francesca','girl',['Italian','Latin'],'from France, free',80,'rising',3,['italian','elegant','romantic'],['Frances','Fran','Francine'],['Frankie','Fran']),
  n('Freya','girl',['Norse'],'goddess of love and fertility',40,'rising',2,['norse','goddess','modern'],['Freyja','Freja','Ingrid'],[]),
  n('Gemma','girl',['Italian','Latin'],'precious stone',65,'rising',2,['italian','jewel','elegant'],['Jemima','Gem','Emma'],[]),
  n('Georgia','girl',['Greek'],'farmer',55,'rising',3,['classic','place','royal'],['Georgiana','Georgina','Jo'],['Georgie','Jo']),
  n('Georgina','girl',['Greek'],'farmer',95,'stable',3,['classic','elegant','royal'],['Georgia','Georgiana','Jo'],['Georgie','Jo']),
  n('Genevieve','girl',['French','Celtic'],'tribe woman',55,'rising',4,['french','vintage','elegant'],['Genny','Viv','Vivienne'],['Gen','Ginny','Evie']),
  n('Gianna','girl',['Italian','Hebrew'],'God is gracious',38,'rising',3,['italian','modern','religious'],['Gia','Giovanna','Jane'],['Gia']),
  n('Gloria','girl',['Latin'],'glory',110,'stable',3,['religious','latin','vintage'],['Glory','Gloriana','Aurora'],[]),
  n('Grace','girl',['Latin'],'grace of God',19,'stable',1,['virtue','classic','popular'],['Gracie','Gracia','Faith'],['Gracie']),
  n('Gracie','girl',['Latin'],'grace',70,'stable',3,['virtue','sweet','modern'],['Grace','Gracia','Gracy'],[]),
  n('Greta','girl',['Germanic'],'pearl',90,'rising',2,['german','vintage','nordic'],['Margaret','Margot','Gretta'],[]),
  n('Hadley','girl',['English'],'heather meadow',75,'rising',3,['english','nature','modern'],['Hailey','Harlow','Hadlee'],[]),
  n('Hailey','girl',['English'],'hero',42,'stable',3,['modern','popular','nature'],['Hayley','Hailee','Hadley'],[]),
  n('Hannah','girl',['Hebrew'],'grace, favour',11,'stable',2,['biblical','classic','popular'],['Anna','Ana','Hanna'],['Han']),
  n('Harriet','girl',['Germanic'],'home ruler',85,'rising',3,['vintage','royal','classic'],['Hattie','Harriett','Henrietta'],['Hattie','Hatty']),
  n('Haven','girl',['English'],'safe place',80,'rising',2,['nature','modern','peaceful'],['Heaven','Harper','Harlow'],[]),
  n('Hazel','girl',['English'],'hazelnut tree',30,'rising',2,['nature','vintage','modern'],['Harriet','Holly','Ivy'],['Haze']),
  n('Heather','girl',['English'],'heather plant',110,'stable',2,['nature','scottish','vintage'],['Heidi','Holly','Hazel'],[]),
  n('Helena','girl',['Greek'],'shining light',65,'rising',3,['greek','royal','classic'],['Helen','Elena','Eleanor'],['Lena','Nellie']),
  n('Hollie','girl',['English'],'holly tree',110,'stable',3,['nature','christmas','british'],['Holly','Hollis','Mollie'],[]),
  n('Holly','girl',['English'],'holly tree',75,'stable',2,['nature','christmas','classic'],['Hollie','Hollis','Ivy'],[]),
  n('Hope','girl',['English'],'hope, expectation',70,'stable',1,['virtue','religious','classic'],['Faith','Grace','Joy'],[]),
  n('Imogen','girl',['Celtic'],'maiden',85,'rising',3,['celtic','literary','vintage'],['Imogene','Imo','Immy'],['Immie','Immy']),
  n('India','girl',['English'],'land of the Indus',95,'rising',3,['place','exotic','modern'],['Indiana','Indie','Lydia'],['Indie']),
  n('Indie','girl',['English'],'independent',100,'rising',3,['modern','edgy','free'],['India','Indy','Ivy'],[]),
  n('Ingrid','girl',['Norse'],'Ing\'s beauty',105,'rising',2,['norse','nordic','elegant'],['Astrid','Sigrid','Freya'],[]),
  n('Iris','girl',['Greek'],'rainbow',46,'rising',2,['greek','nature','vintage'],['Irene','Ivy','Isa'],[]),
  n('Isabel','girl',['Spanish','Hebrew'],'devoted to God',50,'stable',3,['spanish','biblical','classic'],['Isabella','Isabelle','Isobel'],['Izzy','Bella','Belle']),
  n('Isabelle','girl',['French','Hebrew'],'devoted to God',45,'stable',3,['french','romantic','classic'],['Isabella','Isabel','Belle'],['Belle','Izzy']),
  n('Isla','girl',['Scottish'],'island',28,'rising',2,['scottish','nature','modern'],['Isla','Islay','Ayla'],[]),
  n('Ivy','girl',['English'],'ivy plant',33,'rising',2,['nature','vintage','modern'],['Iris','Rose','Violet'],[]),
  n('Jade','girl',['Spanish'],'jade stone',72,'stable',1,['jewel','nature','modern'],['Jada','Jade','Jewel'],[]),
  n('Jasmine','girl',['Persian'],'jasmine flower',56,'stable',3,['flower','persian','modern'],['Jessamine','Yasmin','Jazmine'],['Jazz','Jaz']),
  n('Jenna','girl',['Welsh','English'],'white shadow',90,'stable',2,['welsh','modern','popular'],['Jennifer','Jenny','Gemma'],['Jen']),
  n('Jennifer','girl',['Welsh'],'white shadow, fair one',78,'stable',4,['welsh','vintage','popular'],['Jenna','Jenny','Guinevere'],['Jen','Jenny']),
  n('Jessica','girl',['Hebrew'],'rich, God beholds',56,'stable',3,['biblical','popular','classic'],['Jessie','Jesse','Josephine'],['Jess','Jessie']),
  n('Josephine','girl',['Hebrew','French'],'God will add',47,'rising',3,['french','vintage','royal'],['Josie','Jo','Joanna'],['Josie','Jo','Fifi']),
  n('Joy','girl',['English'],'happiness',92,'stable',1,['virtue','classic','cheerful'],['Joyce','Joyous','Bliss'],[]),
  n('Julia','girl',['Latin'],'youthful',43,'stable',3,['roman','classic','elegant'],['Julie','Juliet','Giulia'],['Jules']),
  n('Juliet','girl',['French','Latin'],'youthful',49,'rising',3,['french','romantic','literary'],['Julia','Juliette','Jules'],['Jules','Julie']),
  n('June','girl',['Latin'],'born in June',82,'rising',1,['month','vintage','classic'],['July','Joy','Luna'],[]),
  n('Katherine','girl',['Greek'],'pure',44,'stable',3,['greek','royal','classic'],['Kathryn','Catherine','Kate'],['Kate','Kathy','Kat']),
  n('Katelyn','girl',['Irish'],'pure, innocent',88,'stable',3,['irish','modern','popular'],['Caitlin','Kaitlyn','Kate'],['Kate','Katey']),
  n('Katie','girl',['Greek'],'pure',82,'stable',3,['greek','popular','sweet'],['Kate','Katherine','Kaitlyn'],[]),
  n('Kayla','girl',['Arabic','Hebrew'],'crown, laurel',68,'stable',2,['arabic','modern','popular'],['Kylie','Kayleigh','Mikayla'],[]),
  n('Kezia','girl',['Hebrew'],'cassia tree, cinnamon',180,'rising',3,['biblical','rare','nature'],['Keziah','Cassia','Casia'],['Kezi']),
  n('Kiera','girl',['Irish'],'dark-haired one',115,'stable',3,['irish','dark','spirited'],['Ciara','Kira','Kyra'],[]),
  n('Lacey','girl',['French','English'],'from Lacy, France',96,'stable',3,['french','modern','sweet'],['Lacie','Lily','Lucy'],['Lace']),
  n('Laura','girl',['Latin'],'bay laurel',73,'stable',2,['roman','classic','elegant'],['Lauren','Laurie','Lara'],['Laurie']),
  n('Lauren','girl',['French','Latin'],'bay laurel',60,'stable',2,['classic','popular','modern'],['Laura','Laurie','Lara'],['Laurie']),
  n('Layla','girl',['Arabic'],'night, dark beauty',17,'rising',3,['arabic','romantic','modern'],['Lila','Lilah','Leila'],[]),
  n('Leah','girl',['Hebrew'],'weary, delicate',21,'stable',2,['biblical','classic','popular'],['Lea','Lia','Lee'],['Lee']),
  n('Lena','girl',['Greek','German'],'light, bright',79,'rising',2,['german','scandinavian','classic'],['Helena','Elena','Selena'],[]),
  n('Leonie','girl',['French','Latin'],'lion-hearted',105,'rising',3,['french','strong','vintage'],['Leona','Leonora','Leone'],[]),
  n('Lexi','girl',['Greek'],'defender of mankind',88,'stable',3,['greek','modern','popular'],['Alexis','Alexa','Alexandra'],['Lex']),
  n('Libby','girl',['Hebrew'],'my God is an oath',92,'stable',2,['hebrew','vintage','sweet'],['Elizabeth','Liberty','Lily'],['Lib']),
  n('Lila','girl',['Arabic','Hebrew'],'night, dark',53,'rising',2,['arabic','persian','elegant'],['Lilah','Leila','Layla'],[]),
  n('Liliana','girl',['Latin'],'lily',54,'rising',4,['latin','flower','elegant'],['Lily','Lillian','Lilia'],['Lily','Lili','Ana']),
  n('Lillian','girl',['Latin'],'lily flower',36,'rising',3,['latin','vintage','flower'],['Lily','Lilly','Liliana'],['Lily','Lillie']),
  n('Lily','girl',['English','Latin'],'lily flower',12,'rising',2,['flower','nature','elegant'],['Lillian','Liliana','Lila'],['Lil']),
  n('Lisa','girl',['Hebrew'],'my God is an oath',108,'stable',2,['classic','vintage','popular'],['Elizabeth','Elisa','Elise'],[]),
  n('Lola','girl',['Spanish'],'sorrows, strong woman',67,'rising',2,['spanish','vivacious','vintage'],['Dolores','Lolita','Lila'],[]),
  n('Lorraine','girl',['French'],'from Lorraine, France',145,'stable',2,['french','place','vintage'],['Lauren','Laura','Loretta'],[]),
  n('Lottie','girl',['French','Germanic'],'free woman',78,'rising',2,['french','vintage','sweet'],['Charlotte','Lotte','Dotty'],[]),
  n('Louise','girl',['French','Germanic'],'famous warrior',86,'rising',2,['french','royal','vintage'],['Louisa','Lucy','Luisa'],['Lou','Lulu']),
  n('Lucia','girl',['Latin'],'light',51,'rising',3,['latin','italian','elegant'],['Lucy','Lucie','Luciana'],['Lu']),
  n('Lucinda','girl',['Latin'],'light',118,'stable',3,['latin','vintage','elegant'],['Lucy','Lucia','Linda'],['Lucy','Cindy']),
  n('Lucy','girl',['Latin'],'light',13,'rising',2,['latin','classic','popular'],['Lucia','Lucinda','Lucie'],[]),
  n('Lydia','girl',['Greek'],'from Lydia, Greece',44,'rising',3,['biblical','vintage','classic'],['Lydie','Linda','Claudia'],['Liddy']),
  n('Mabel','girl',['Latin'],'lovable',90,'rising',2,['vintage','latin','sweet'],['Mable','Amabel','Mae'],['Mae','Mab']),
  n('Maddison','girl',['English'],'son of Matthew',74,'stable',3,['modern','popular','place'],['Madison','Maddie','Madie'],['Maddie']),
  n('Madison','girl',['English'],'son of Matthew',63,'stable',3,['modern','popular','place'],['Maddison','Maddie','Madie'],['Maddie','Maddy']),
  n('Mae','girl',['English','Latin'],'pearl, great',84,'rising',1,['vintage','short','sweet'],['May','Mabel','Maeve'],[]),
  n('Maeve','girl',['Irish'],'she who intoxicates',39,'rising',2,['irish','mythological','strong'],['Mae','Mavis','Maylene'],[]),
  n('Maggie','girl',['Greek'],'pearl',77,'stable',2,['greek','vintage','popular'],['Margaret','Margot','Magdalene'],['Mags']),
  n('Margaret','girl',['Greek'],'pearl',83,'rising',3,['classic','royal','vintage'],['Maggie','Margot','Greta'],['Maggie','Meg','Peggy']),
  n('Margot','girl',['French'],'pearl',57,'rising',2,['french','chic','vintage'],['Margaret','Margaux','Margo'],['Margo']),
  n('Maria','girl',['Hebrew','Latin'],'sea of bitterness',72,'stable',3,['biblical','classic','spanish'],['Mary','Marie','Marina'],['Mari']),
  n('Mariana','girl',['Spanish','Latin'],'grace + sea of bitterness',81,'stable',4,['spanish','romantic','classic'],['Maria','Marina','Marianna'],['Mari','Ana']),
  n('Marie','girl',['French'],'sea of bitterness',93,'stable',2,['french','classic','biblical'],['Mary','Maria','Marina'],['Mari']),
  n('Marina','girl',['Latin'],'of the sea',86,'rising',3,['latin','nature','elegant'],['Maria','Marine','Mara'],['Mari']),
  n('Mary','girl',['Hebrew'],'sea of bitterness',97,'stable',2,['biblical','classic','royal'],['Marie','Maria','Mae'],['Molly','Polly']),
  n('Matilda','girl',['Germanic'],'mighty in battle',62,'rising',3,['germanic','vintage','royal'],['Mathilde','Tilly','Tildie'],['Tillie','Tilly','Mattie']),
  n('Maya','girl',['Hebrew','Sanskrit'],'water, illusion',23,'stable',2,['hebrew','sanskrit','popular'],['Mia','Mya','Amaya'],[]),
  n('Megan','girl',['Welsh'],'pearl',76,'stable',2,['welsh','popular','modern'],['Meghan','Meagan','Margaret'],['Meg','Meggie']),
  n('Melissa','girl',['Greek'],'honey bee',89,'stable',3,['greek','sweet','popular'],['Melanie','Melodie','Alyssa'],['Missy','Mel','Lisa']),
  n('Meredith','girl',['Welsh'],'great ruler',100,'stable',3,['welsh','vintage','strong'],['Merideth','Morgan','Gwyneth'],['Meri','Merry']),
  n('Mia','girl',['Scandinavian','Italian'],'mine, beloved',8,'stable',2,['short','popular','modern'],['Maya','Mya','Mia'],[]),
  n('Michelle','girl',['Hebrew','French'],'who is like God',78,'stable',2,['french','biblical','classic'],['Michaela','Michele','Micaela'],['Micki','Mickey','Shelly']),
  n('Millie','girl',['Germanic'],'gentle strength',48,'rising',2,['vintage','sweet','popular'],['Milly','Amelia','Mildred'],[]),
  n('Miranda','girl',['Latin'],'worthy of admiration',96,'stable',3,['latin','literary','romantic'],['Maranda','Miranda','Amanda'],['Randi','Mandy']),
  n('Molly','girl',['Irish','Hebrew'],'sea of bitterness',37,'stable',2,['irish','sweet','popular'],['Mollie','Mary','Margaret'],[]),
  n('Morgan','girl',['Welsh'],'sea-born, great',53,'stable',2,['welsh','neutral','modern'],['Morrigan','Morgana','Morgen'],[]),
  n('Naomi','girl',['Hebrew'],'pleasant, good',32,'rising',3,['biblical','elegant','modern'],['Naomi','Nomi','Noemi'],['Nomi']),
  n('Natalia','girl',['Latin'],'birthday, Christmas Day',64,'rising',4,['latin','russian','romantic'],['Natalie','Natasha','Natalya'],['Nat','Natty']),
  n('Natalie','girl',['Latin'],'birthday, Christmas Day',41,'stable',3,['latin','popular','classic'],['Natalia','Natasha','Nicole'],['Nat','Natty']),
  n('Natasha','girl',['Russian'],'birthday, Christmas',91,'stable',3,['russian','romantic','elegant'],['Natalia','Natalie','Sasha'],['Tasha','Nat']),
  n('Nell','girl',['English','Greek'],'bright, shining',102,'rising',1,['vintage','short','sweet'],['Nellie','Eleanor','Helen'],['Nellie']),
  n('Nicole','girl',['Greek','French'],'victorious people',66,'stable',2,['french','popular','classic'],['Nicolette','Nicola','Nikki'],['Nikki','Niki']),
  n('Nora','girl',['Irish','Latin'],'honour, light',29,'rising',2,['irish','elegant','popular'],['Norah','Eleanor','Honora'],[]),
  n('Norah','girl',['Irish'],'honour',82,'rising',2,['irish','vintage','elegant'],['Nora','Eleanor','Honora'],[]),
  n('Octavia','girl',['Latin'],'eighth',115,'rising',4,['roman','vintage','regal'],['Ottavia','Tavia','Avia'],['Tavi','Tavia']),
  n('Olivia','girl',['Latin'],'olive tree',2,'rising',4,['classic','popular','nature'],['Olive','Livia','Alivia'],['Liv','Livvy']),
  n('Ophelia','girl',['Greek'],'help',95,'rising',4,['greek','literary','romantic'],['Ofelia','Ophie','Felicia'],['Ophie']),
  n('Paige','girl',['French','English'],'page, attendant',76,'stable',1,['modern','french','popular'],['Page','Paige','Leigh'],[]),
  n('Paisley','girl',['Scottish'],'patterned fabric, place name',43,'rising',3,['scottish','modern','spirited'],['Presley','Brisley','Pasley'],[]),
  n('Phoebe','girl',['Greek'],'bright, radiant',34,'rising',2,['greek','mythological','vintage'],['Pheobe','Phebe','Penelope'],['Pheebs']),
  n('Piper','girl',['English'],'one who plays pipes',61,'rising',2,['english','musical','modern'],['Pepper','Pippa','Parker'],[]),
  n('Poppy','girl',['English'],'flower',66,'rising',2,['flower','nature','british'],['Penny','Polly','Lily'],[]),
  n('Priya','girl',['Sanskrit'],'beloved, dear',102,'rising',3,['indian','sanskrit','popular'],['Priyanka','Pria','Preeti'],[]),
  n('Rachel','girl',['Hebrew'],'female sheep, innocent',68,'stable',2,['biblical','classic','popular'],['Rachael','Rachelle','Rae'],['Rae','Rach']),
  n('Rebecca','girl',['Hebrew'],'to bind, captivating',69,'stable',3,['biblical','classic','popular'],['Rebekah','Becca','Becky'],['Becca','Becky','Reba']),
  n('Rhiannon','girl',['Welsh'],'divine queen',108,'rising',3,['welsh','mythological','musical'],['Rhianna','Rihanna','Brianna'],['Rhi','Rhia']),
  n('Robyn','girl',['Germanic'],'bright fame',112,'stable',2,['germanic','vintage','nature'],['Robin','Roberta','Robyn'],[]),
  n('Rosa','girl',['Latin'],'rose flower',78,'rising',2,['latin','flower','elegant'],['Rose','Rosie','Rosalie'],['Rosie']),
  n('Rosalie','girl',['French','Latin'],'rose',72,'rising',4,['french','flower','elegant'],['Rosa','Rosalia','Rose'],['Rosie','Rosy']),
  n('Rose','girl',['Latin'],'rose flower',41,'rising',1,['flower','nature','classic'],['Rosa','Rosie','Rosalie'],['Rosie']),
  n('Rosie','girl',['Latin'],'rose',64,'rising',3,['flower','sweet','british'],['Rose','Rosa','Rosalie'],[]),
  n('Ruby','girl',['Latin'],'red gemstone',26,'rising',2,['jewel','nature','vintage'],['Rubi','Rubee','Rose'],[]),
  n('Ruth','girl',['Hebrew'],'companion, friend',96,'stable',1,['biblical','classic','strong'],['Rose','Rue','Ruthy'],['Ruthy']),
  n('Sadie','girl',['Hebrew'],'princess',47,'rising',3,['hebrew','vintage','sweet'],['Sarah','Sara','Sade'],[]),
  n('Samantha','girl',['Aramaic'],'told by God',58,'stable',3,['aramaic','popular','modern'],['Samara','Samira','Sienna'],['Sam','Sammy']),
  n('Sara','girl',['Hebrew'],'princess',81,'stable',2,['biblical','classic','popular'],['Sarah','Zara','Kara'],['Sarry']),
  n('Sarah','girl',['Hebrew'],'princess',15,'stable',2,['biblical','classic','royal'],['Sara','Sadie','Zara'],['Sadie','Sally']),
  n('Sasha','girl',['Russian','Greek'],'defending warrior',97,'stable',2,['russian','neutral','modern'],['Natasha','Tasha','Sandra'],[]),
  n('Savannah','girl',['Spanish'],'treeless plain',44,'stable',3,['place','nature','southern'],['Savanna','Hannah','Savan'],['Sav','Vannah']),
  n('Scarlett','girl',['English'],'bright red',16,'rising',2,['colour','modern','bold'],['Scarlet','Ruby','Violet'],['Scar']),
  n('Selena','girl',['Greek'],'moon',83,'rising',3,['greek','celestial','romantic'],['Selene','Serena','Elena'],[]),
  n('Serena','girl',['Latin'],'calm, serene',84,'rising',3,['latin','elegant','peaceful'],['Selena','Sienna','Sabrina'],['Rena']),
  n('Sienna','girl',['Italian'],'orange-red, from Siena',47,'rising',3,['italian','place','colour'],['Siena','Selena','Sabrina'],[]),
  n('Sierra','girl',['Spanish'],'mountain range',79,'stable',3,['spanish','nature','place'],['Sienna','Ciara','Sabrina'],[]),
  n('Skylar','girl',['Dutch'],'scholar',57,'rising',3,['dutch','modern','neutral'],['Skye','Skyler','Taylor'],[]),
  n('Skye','girl',['Scottish'],'sky',83,'rising',1,['nature','scottish','modern'],['Skylar','Skyler','Blair'],[]),
  n('Sofia','girl',['Greek'],'wisdom',10,'rising',3,['greek','popular','elegant'],['Sophia','Sophie','Sofie'],['Sofie']),
  n('Sophie','girl',['French','Greek'],'wisdom',11,'stable',2,['french','popular','sweet'],['Sophia','Sofia','Sofie'],[]),
  n('Stella','girl',['Latin'],'star',20,'rising',2,['latin','celestial','vintage'],['Estella','Estrella','Estelle'],[]),
  n('Stephanie','girl',['Greek'],'crown, garland',84,'stable',3,['greek','popular','classic'],['Stefanie','Stevie','Stephania'],['Stevie','Steph']),
  n('Summer','girl',['English'],'summer season',63,'stable',2,['season','nature','modern'],['Autumn','Sunny','Sommer'],[]),
  n('Susan','girl',['Hebrew'],'lily',118,'stable',2,['biblical','vintage','classic'],['Susannah','Susanne','Sue'],['Sue','Susie']),
  n('Susannah','girl',['Hebrew'],'lily, rose',108,'rising',3,['biblical','vintage','elegant'],['Susan','Susanna','Suzannah'],['Susie','Sue','Anna']),
  n('Sybil','girl',['Greek'],'prophetess',145,'rising',2,['greek','vintage','literary'],['Sibyl','Cybil','Sibella'],[]),
  n('Tabitha','girl',['Aramaic'],'gazelle',105,'rising',3,['aramaic','biblical','vintage'],['Tabby','Tabi','Abitha'],['Tabby']),
  n('Tamara','girl',['Hebrew'],'palm tree',106,'stable',3,['hebrew','biblical','elegant'],['Tamsin','Tammy','Tamera'],['Tammy','Tami']),
  n('Tara','girl',['Irish','Sanskrit'],'hill, star',99,'stable',2,['irish','sanskrit','classic'],['Tiara','Tamara','Cara'],[]),
  n('Tessa','girl',['Greek'],'to harvest',79,'rising',2,['greek','vintage','sweet'],['Theresa','Teresa','Tess'],['Tess']),
  n('Thea','girl',['Greek'],'goddess, godly',59,'rising',2,['greek','elegant','vintage'],['Theodora','Dorothea','Theia'],[]),
  n('Theodora','girl',['Greek'],'gift of God',87,'rising',4,['greek','vintage','royal'],['Thea','Dorothy','Dorothea'],['Thea','Teddy','Dora']),
  n('Valentina','girl',['Latin'],'strong, healthy',62,'rising',4,['latin','romantic','elegant'],['Valentine','Val','Valeria'],['Val','Tina']),
  n('Valeria','girl',['Latin'],'strong, healthy',69,'rising',4,['latin','roman','elegant'],['Valentina','Vale','Valerie'],['Val']),
  n('Valerie','girl',['Latin'],'strong, healthy',80,'stable',3,['latin','classic','popular'],['Valeria','Valentina','Val'],['Val']),
  n('Vanessa','girl',['Greek'],'butterfly',86,'stable',3,['greek','modern','literary'],['Janessa','Nessa','Vana'],['Nessa','Vann']),
  n('Vera','girl',['Latin','Russian'],'true, faith',74,'rising',2,['latin','russian','vintage'],['Verity','Veronika','Vere'],[]),
  n('Veronica','girl',['Greek','Latin'],'true image',89,'stable',4,['religious','classic','elegant'],['Vera','Veronika','Veronique'],['Roni','Ronnie','Nikki']),
  n('Victoria','girl',['Latin'],'victory',38,'stable',4,['roman','royal','classic'],['Victoire','Vicky','Vikki'],['Vicky','Tori','Vikki']),
  n('Violet','girl',['Latin'],'purple flower',27,'rising',3,['flower','colour','vintage'],['Viola','Violette','Violet'],['Vi']),
  n('Virginia','girl',['Latin'],'virgin, pure',109,'stable',3,['roman','literary','classic'],['Ginny','Ginger','Vera'],['Ginny','Ginger']),
  n('Vivienne','girl',['French','Latin'],'alive',69,'rising',3,['french','elegant','vintage'],['Vivian','Viv','Viviene'],['Viv','Vivie']),
  n('Whitney','girl',['English'],'white island',118,'stable',2,['english','place','modern'],['Britney','Lindsey','Whitley'],[]),
  n('Wren','girl',['English'],'small bird',67,'rising',1,['nature','bird','modern'],['Ren','Renny','Robin'],[]),
  n('Xanthe','girl',['Greek'],'golden, yellow',165,'rising',2,['greek','rare','vibrant'],['Xander','Zoe','Zoë'],[]),
  n('Yasmin','girl',['Arabic','Persian'],'jasmine flower',88,'rising',2,['arabic','persian','flower'],['Jasmine','Yasmine','Yasmeen'],[]),
  n('Yvette','girl',['French'],'yew wood',145,'stable',2,['french','vintage','classic'],['Yvonne','Ivette','Evette'],[]),
  n('Yvonne','girl',['French'],'yew wood',130,'stable',2,['french','vintage','classic'],['Yvette','Ivonne','Evonne'],[]),
  n('Zara','girl',['Arabic','Hebrew'],'princess, radiance',48,'rising',2,['arabic','modern','royal'],['Sara','Zahra','Zoe'],[]),
  n('Zoe','girl',['Greek'],'life',15,'rising',2,['greek','popular','vibrant'],['Zoey','Zoe','Chloe'],[]),
  n('Zoey','girl',['Greek'],'life',16,'rising',3,['greek','modern','vibrant'],['Zoe','Zoie','Chloe'],[]),

  // ── BOYS ────────────────────────────────────────────────────────────────────
  n('Aaron','boy',['Hebrew'],'high mountain, exalted',27,'stable',2,['biblical','classic','strong'],['Aron','Arron','Ari'],['Ari']),
  n('Abel','boy',['Hebrew'],'breath, vapour',95,'rising',2,['biblical','vintage','short'],['Able','Abe','Cain'],['Abe']),
  n('Adam','boy',['Hebrew'],'man, earth',29,'stable',2,['biblical','classic','strong'],['Adams','Aidan','Ethan'],[]),
  n('Adrian','boy',['Latin'],'from Hadria',36,'stable',3,['roman','classic','strong'],['Adriano','Hadrian','Andre'],[]),
  n('Aiden','boy',['Irish'],'little fire',20,'rising',3,['irish','popular','spirited'],['Aidan','Ayden','Aden'],[]),
  n('Alan','boy',['Celtic','Irish'],'handsome, harmony',85,'stable',2,['celtic','classic','popular'],['Allen','Allan','Al'],['Al']),
  n('Albert','boy',['Germanic'],'noble and bright',88,'rising',2,['germanic','vintage','royal'],['Albie','Alpert','Alfie'],['Al','Albie']),
  n('Albie','boy',['Germanic'],'noble and bright',96,'rising',3,['germanic','sweet','vintage'],['Albert','Alby','Alfie'],[]),
  n('Alec','boy',['Greek'],'defending men',102,'stable',2,['greek','short','modern'],['Alexander','Alex','Aleck'],['Al']),
  n('Alex','boy',['Greek'],'defending men',33,'stable',2,['greek','popular','neutral'],['Alexander','Alexis','Alec'],['Al']),
  n('Alfie','boy',['Germanic'],'elf counsel',70,'rising',3,['british','vintage','sweet'],['Alfred','Albie','Archie'],[]),
  n('Alfred','boy',['Germanic'],'elf counsel',99,'rising',2,['germanic','vintage','royal'],['Alfie','Fred','Freddie'],['Alfie','Fred']),
  n('Ali','boy',['Arabic'],'sublime, noble',75,'stable',2,['arabic','popular','classic'],['Alim','Amir','Ali'],[]),
  n('Andrew','boy',['Greek'],'strong, manly',23,'stable',2,['biblical','classic','royal'],['Andy','Andre','Andreas'],['Andy','Drew']),
  n('Angelo','boy',['Italian','Greek'],'angel, messenger',104,'stable',3,['italian','religious','classic'],['Angel','Angelo','Angus'],[]),
  n('Angus','boy',['Scottish','Celtic'],'one choice',108,'rising',2,['scottish','celtic','strong'],['Augustus','Gus','August'],['Gus']),
  n('Anthony','boy',['Latin'],'priceless one',17,'stable',3,['roman','classic','popular'],['Antonio','Anton','Antonino'],['Tony','Ant']),
  n('Archie','boy',['Germanic'],'truly brave',50,'rising',3,['british','vintage','royal'],['Archer','Archibald','Archi'],[]),
  n('Arnold','boy',['Germanic'],'eagle power',145,'stable',2,['germanic','vintage','strong'],['Arnie','Arnaud','Aaron'],['Arnie']),
  n('Arthur','boy',['Celtic'],'bear',39,'rising',2,['celtic','royal','literary'],['Art','Artie','Arty'],['Art','Artie']),
  n('Ashton','boy',['English'],'ash tree settlement',69,'stable',2,['english','place','modern'],['Asher','Ash','Aston'],['Ash']),
  n('Asher','boy',['Hebrew'],'fortunate, blessed',24,'rising',2,['hebrew','biblical','modern'],['Ash','Asa','Asher'],['Ash']),
  n('Austin','boy',['Latin'],'great, magnificent',42,'stable',2,['latin','place','popular'],['Augustine','Austyn','Austen'],[]),
  n('Axel','boy',['Norse','Hebrew'],'father of peace',52,'rising',2,['norse','modern','strong'],['Alex','Axel','Aksel'],[]),
  n('Barnaby','boy',['Hebrew'],'son of consolation',112,'rising',3,['biblical','vintage','british'],['Barney','Barnabas','Barry'],['Barney']),
  n('Barrett','boy',['Germanic'],'bear strength',91,'rising',2,['germanic','modern','strong'],['Barry','Barnett','Garrett'],[]),
  n('Beckett','boy',['English'],'dweller near the brook',68,'rising',2,['english','literary','modern'],['Beck','Bennett','Brendan'],['Beck']),
  n('Benedict','boy',['Latin'],'blessed',76,'rising',3,['latin','religious','vintage'],['Ben','Benny','Benedikt'],['Ben','Bennie']),
  n('Blake','boy',['English'],'fair-haired, dark',66,'stable',1,['english','neutral','modern'],['Blaine','Blake','Blayke'],[]),
  n('Bradley','boy',['English'],'broad meadow',83,'stable',3,['english','classic','popular'],['Brad','Braden','Brady'],['Brad']),
  n('Brady','boy',['Irish'],'descendant of Bradach',72,'rising',3,['irish','modern','spirited'],['Bradley','Braden','Brody'],['Brad']),
  n('Brandon','boy',['English'],'broom hill',60,'stable',2,['english','classic','popular'],['Brendan','Branden','Brantley'],['Bran']),
  n('Brayden','boy',['Irish'],'descendant of Bradán',74,'rising',3,['irish','modern','popular'],['Braden','Aiden','Caden'],[]),
  n('Brendan','boy',['Irish'],'prince',87,'stable',2,['irish','classic','royal'],['Brandon','Brennan','Brenden'],['Bren']),
  n('Brian','boy',['Irish','Celtic'],'strong, virtuous',78,'stable',2,['irish','classic','strong'],['Bryan','Brien','Bryn'],['Bri']),
  n('Brock','boy',['English'],'badger',104,'stable',1,['english','nature','strong'],['Brook','Rock','Brick'],[]),
  n('Brody','boy',['Scottish','Irish'],'muddy place',62,'rising',2,['scottish','irish','modern'],['Brady','Brodie','Cody'],[]),
  n('Brooks','boy',['English'],'of the brooks',88,'rising',1,['english','nature','modern'],['Brooke','Brook','Brock'],[]),
  n('Bruno','boy',['Germanic'],'brown',109,'rising',2,['germanic','vintage','strong'],['Bruno','Brun','Brune'],[]),
  n('Byron','boy',['English'],'at the byres',118,'stable',2,['english','literary','romantic'],['Brian','Myron','Tyrone'],[]),
  n('Caden','boy',['Welsh','Arabic'],'battle',80,'rising',2,['welsh','modern','spirited'],['Aiden','Jayden','Kaden'],[]),
  n('Caleb','boy',['Hebrew'],'faithful, dog',19,'stable',2,['biblical','classic','popular'],['Cale','Kaleb','Coby'],[]),
  n('Calvin','boy',['Latin'],'bald, hairless',87,'rising',2,['latin','vintage','strong'],['Cal','Colvin','Kevin'],['Cal']),
  n('Cameron','boy',['Scottish'],'crooked nose',53,'stable',3,['scottish','neutral','popular'],['Cameron','Camron','Cam'],['Cam']),
  n('Carl','boy',['Germanic'],'free man',105,'stable',1,['germanic','classic','strong'],['Karl','Charlie','Carlos'],[]),
  n('Carlos','boy',['Spanish'],'free man',56,'stable',2,['spanish','classic','popular'],['Carlo','Carl','Carlos'],[]),
  n('Carson','boy',['Scottish'],'son of Carr',61,'rising',2,['scottish','modern','neutral'],['Carter','Karson','Corson'],[]),
  n('Carter','boy',['English'],'transporter of goods',24,'rising',2,['english','occupational','popular'],['Carson','Carter','Carder'],[]),
  n('Charles','boy',['Germanic'],'free man',13,'stable',2,['germanic','royal','classic'],['Charlie','Chuck','Chaz'],['Charlie','Chuck']),
  n('Charlie','boy',['Germanic'],'free man',10,'rising',3,['germanic','popular','royal'],['Charles','Charley','Chaz'],['Chuck']),
  n('Chase','boy',['French'],'to hunt',54,'stable',1,['french','modern','energetic'],['Chaz','Chase','Chance'],[]),
  n('Chris','boy',['Greek'],'follower of Christ',95,'stable',1,['greek','classic','short'],['Christian','Christopher','Christoph'],['Chris']),
  n('Christian','boy',['Greek'],'follower of Christ',35,'stable',3,['greek','religious','classic'],['Christiano','Chris','Kristian'],['Chris','Christie']),
  n('Christopher','boy',['Greek'],'bearer of Christ',21,'stable',3,['greek','biblical','classic'],['Chris','Kristopher','Topher'],['Chris','Kit','Topher']),
  n('Cian','boy',['Irish'],'ancient',98,'rising',2,['irish','gaelic','vintage'],['Cian','Kian','Ciaran'],[]),
  n('Ciaran','boy',['Irish'],'little dark one',106,'rising',3,['irish','gaelic','dark'],['Kieran','Cian','Kiran'],[]),
  n('Clyde','boy',['Scottish'],'river in Scotland',118,'rising',1,['scottish','place','vintage'],['Clydie','Lloyd','Floyd'],[]),
  n('Cole','boy',['English','Greek'],'victorious people',46,'stable',1,['english','short','modern'],['Colin','Coleman','Colby'],[]),
  n('Colin','boy',['Irish','Greek'],'young creature',79,'stable',2,['irish','classic','popular'],['Cole','Collin','Nicholas'],['Col']),
  n('Colton','boy',['English'],'from the coal town',55,'stable',2,['english','modern','place'],['Cole','Colby','Colt'],['Colt']),
  n('Conor','boy',['Irish'],'lover of hounds',66,'stable',2,['irish','classic','popular'],['Connor','Conner','Conn'],['Con']),
  n('Cooper','boy',['English'],'barrel maker',38,'rising',2,['english','occupational','popular'],['Cooper','Coby','Cosper'],['Coop']),
  n('Cormac','boy',['Irish'],'charioteer',115,'rising',2,['irish','gaelic','mythological'],['Cormack','Cory','Mac'],['Mac']),
  n('Damian','boy',['Greek'],'to tame, subdue',72,'stable',3,['greek','religious','classic'],['Damien','Damon','Adrian'],['Dami']),
  n('Dante','boy',['Italian','Latin'],'enduring',85,'rising',2,['italian','literary','artistic'],['Dante','Dant','Daniel'],[]),
  n('Darius','boy',['Persian'],'possesses goodness',96,'rising',3,['persian','strong','classic'],['Darian','Darrell','Dario'],[]),
  n('David','boy',['Hebrew'],'beloved',8,'stable',2,['biblical','classic','royal'],['Dave','Davie','Davis'],['Dave','Davie']),
  n('Declan','boy',['Irish'],'man of prayer',49,'rising',2,['irish','gaelic','strong'],['Dec','Declen','Dex'],['Dec']),
  n('Dennis','boy',['Greek'],'follower of Dionysius',115,'stable',2,['greek','classic','vintage'],['Denis','Dean','Danny'],['Denny']),
  n('Desmond','boy',['Irish'],'from south Munster',101,'rising',2,['irish','gaelic','vintage'],['Des','Dezzy','Desi'],['Des','Desi']),
  n('Dexter','boy',['Latin'],'right-handed, skilled',73,'rising',2,['latin','modern','strong'],['Dex','Devin','Dean'],['Dex']),
  n('Dominic','boy',['Latin'],'of the Lord',40,'stable',3,['latin','religious','classic'],['Dom','Dominick','Nick'],['Dom','Nick']),
  n('Dylan','boy',['Welsh'],'son of the sea',26,'stable',2,['welsh','musical','popular'],['Dillon','Dyland','Dyl'],['Dyl']),
  n('Eddie','boy',['Germanic'],'rich guard',90,'rising',2,['germanic','vintage','sweet'],['Edward','Edmund','Edwin'],['Ed']),
  n('Edmund','boy',['Germanic'],'rich protection',103,'rising',2,['germanic','royal','literary'],['Edward','Edmond','Ed'],['Ed','Ned']),
  n('Edward','boy',['Germanic'],'rich guard',30,'rising',2,['germanic','royal','classic'],['Eddie','Ned','Ted'],['Ed','Eddie','Ned','Ted']),
  n('Eli','boy',['Hebrew'],'ascended, my God',22,'rising',2,['biblical','short','popular'],['Elijah','Elias','Elliot'],['El']),
  n('Elias','boy',['Greek','Hebrew'],'my God is Yahweh',31,'rising',3,['biblical','classic','rising'],['Elijah','Eli','Elijah'],[]),
  n('Elliott','boy',['English','Hebrew'],'the Lord is my God',44,'rising',3,['english','literary','modern'],['Elliot','Eli','Elias'],['Eli']),
  n('Ellis','boy',['Welsh','English'],'benevolent',82,'rising',2,['welsh','neutral','vintage'],['Eli','Ellery','Elvis'],[]),
  n('Emmanuel','boy',['Hebrew'],'God is with us',71,'stable',4,['biblical','religious','classic'],['Emile','Emilio','Manny'],['Manny']),
  n('Emmett','boy',['Germanic'],'whole, universal',63,'rising',2,['germanic','literary','vintage'],['Emma','Emmet','Emerson'],['Em']),
  n('Enzo','boy',['Italian','Germanic'],'ruler of the home',57,'rising',2,['italian','modern','strong'],['Lorenzo','Lenzo','Renzo'],[]),
  n('Eric','boy',['Norse'],'eternal ruler',71,'stable',2,['norse','classic','popular'],['Erik','Erick','Erica'],[]),
  n('Evan','boy',['Welsh'],'God is gracious',48,'stable',2,['welsh','popular','classic'],['Ewan','Ian','Ivan'],[]),
  n('Everett','boy',['Germanic'],'strong as a boar',64,'rising',3,['germanic','vintage','modern'],['Everly','Everest','Rhett'],['Rhett','Ev']),
  n('Ezra','boy',['Hebrew'],'help',25,'rising',2,['biblical','vintage','modern'],['Eza','Ezri','Ozzy'],[]),
  n('Fabian','boy',['Latin'],'bean grower',104,'rising',3,['latin','roman','vintage'],['Fabio','Fabien','Sebastian'],[]),
  n('Felix','boy',['Latin'],'happy, fortunate',37,'rising',2,['latin','cheerful','vintage'],['Felicio','Phelix','Eli'],[]),
  n('Fergus','boy',['Irish','Scottish'],'strong man',110,'rising',2,['irish','scottish','strong'],['Fergie','Ferg','Finn'],['Fergie']),
  n('Fernando','boy',['Spanish','Germanic'],'bold voyager',87,'stable',3,['spanish','classic','adventurous'],['Ferdinand','Hernando','Nando'],['Nando']),
  n('Finn','boy',['Irish'],'fair',36,'rising',1,['irish','short','nature'],['Finley','Fintan','Fionn'],[]),
  n('Finley','boy',['Irish','Scottish'],'fair-haired hero',47,'rising',3,['irish','scottish','modern'],['Finn','Findlay','Finlay'],['Finn']),
  n('Fionn','boy',['Irish'],'fair, white',88,'rising',1,['irish','gaelic','nature'],['Finn','Fionn','Fionnbarra'],[]),
  n('Fletcher','boy',['English'],'arrow maker',95,'rising',2,['english','occupational','modern'],['Fletch','Fletcher','Francis'],['Fletch']),
  n('Floyd','boy',['Welsh'],'grey-haired',125,'stable',1,['welsh','vintage','classic'],['Lloyd','Clyde','Floyd'],[]),
  n('Flynn','boy',['Irish'],'son of the red-haired one',82,'rising',1,['irish','modern','spirited'],['Finn','Flyn','Lyn'],[]),
  n('Francis','boy',['Latin'],'Frenchman',92,'rising',3,['latin','religious','classic'],['Frank','Frankie','Francisco'],['Frank','Frankie']),
  n('Frank','boy',['Germanic'],'free man',93,'rising',1,['germanic','vintage','classic'],['Francis','Frankie','Franklin'],['Frankie']),
  n('Frankie','boy',['Germanic'],'free man',88,'rising',3,['germanic','sweet','vintage'],['Frank','Francis','Franklin'],[]),
  n('Franklin','boy',['Germanic'],'free landowner',97,'stable',2,['germanic','classic','vintage'],['Frank','Frankie','Lincoln'],['Frank','Frankie']),
  n('Fraser','boy',['Scottish'],'of the forest men',102,'rising',2,['scottish','nature','classic'],['Frasier','Frazer','Fraser'],[]),
  n('Freddie','boy',['Germanic'],'peaceful ruler',69,'rising',3,['germanic','vintage','royal'],['Fred','Frederick','Freddy'],[]),
  n('Frederick','boy',['Germanic'],'peaceful ruler',78,'rising',3,['germanic','royal','classic'],['Freddie','Fred','Fritz'],['Fred','Freddie']),
  n('Gabriel','boy',['Hebrew'],'God is my strength',28,'rising',3,['biblical','elegant','classic'],['Gabe','Gabi','Gabby'],['Gabe']),
  n('Garrett','boy',['Germanic'],'spear strength',83,'stable',2,['germanic','modern','strong'],['Gareth','Garret','Gerard'],[]),
  n('George','boy',['Greek'],'farmer',16,'rising',2,['greek','royal','classic'],['Georgie','Greg','Georg'],['Georgie']),
  n('Gerald','boy',['Germanic'],'spear ruler',110,'stable',2,['germanic','vintage','classic'],['Gerard','Jerald','Jerry'],['Jerry','Gerry']),
  n('Giovanni','boy',['Italian','Hebrew'],'God is gracious',92,'rising',4,['italian','biblical','romantic'],['Gianni','Giovanni','Ivan'],['Gianni']),
  n('Glenn','boy',['Scottish','Irish'],'valley',108,'stable',1,['scottish','nature','classic'],['Glen','Glynn','Flynn'],[]),
  n('Graham','boy',['Scottish'],'grey home',76,'rising',2,['scottish','classic','strong'],['Graeme','Gray','Greyson'],['Gray']),
  n('Grant','boy',['Scottish','French'],'great',82,'stable',1,['scottish','short','strong'],['Grantham','Granville','Brant'],[]),
  n('Gregory','boy',['Greek'],'watchful, alert',95,'stable',3,['greek','classic','religious'],['Greg','Gregg','Grey'],['Greg']),
  n('Griffin','boy',['Welsh'],'strong lord',69,'rising',2,['welsh','mythological','strong'],['Griff','Griffith','Grimm'],['Griff']),
  n('Hamish','boy',['Scottish'],'supplanter',99,'rising',2,['scottish','gaelic','vintage'],['James','Jamie','Seamus'],[]),
  n('Harley','boy',['English'],'hare meadow',90,'stable',2,['english','nature','neutral'],['Harlow','Harvey','Harper'],[]),
  n('Harrison','boy',['English'],'son of Harry',54,'stable',3,['english','presidential','popular'],['Harry','Harris','Harvey'],['Harry']),
  n('Harvey','boy',['Celtic','French'],'battle worthy',67,'rising',2,['celtic','vintage','british'],['Harry','Harley','Harris'],['Harv']),
  n('Hector','boy',['Greek'],'holding fast',86,'rising',2,['greek','mythological','strong'],['Hector','Hektor','Nestor'],[]),
  n('Hugh','boy',['Germanic'],'heart, mind',97,'stable',1,['germanic','royal','classic'],['Hugo','Hughes','Huw'],[]),
  n('Hugo','boy',['Germanic'],'heart, mind',57,'rising',2,['germanic','royal','modern'],['Hugh','Hugo','Ugo'],[]),
  n('Hunter','boy',['English'],'one who hunts',41,'stable',2,['english','occupational','modern'],['Hunt','Hunter','Gunner'],[]),
  n('Isaac','boy',['Hebrew'],'he will laugh',18,'stable',3,['biblical','classic','popular'],['Izaak','Isaiah','Ike'],['Ike','Zac']),
  n('Isaiah','boy',['Hebrew'],'salvation of God',15,'rising',3,['biblical','spiritual','classic'],['Isiah','Isaias','Elijah'],['Ike','Zay']),
  n('Ivan','boy',['Russian','Slavic'],'God is gracious',67,'stable',2,['russian','slavic','classic'],['Ivo','Ian','Igor'],[]),
  n('Jack','boy',['English','Hebrew'],'God is gracious',9,'stable',1,['english','classic','royal'],['John','Jake','Jackson'],[]),
  n('Jackson','boy',['English'],'son of Jack',12,'stable',2,['english','modern','popular'],['Jack','Jaxon','Jaxson'],['Jack','Jax']),
  n('Jasper','boy',['Persian'],'bringer of treasure',56,'rising',2,['persian','gemstone','vintage'],['Casper','Kasper','Jaspar'],[]),
  n('Jaxon','boy',['English'],'God has been gracious',32,'rising',2,['english','modern','popular'],['Jackson','Jax','Jaxson'],['Jax']),
  n('Jayden','boy',['Hebrew'],'thankful',30,'stable',3,['hebrew','modern','popular'],['Jaiden','Jaden','Aiden'],['Jay']),
  n('Jefferson','boy',['English'],'son of Jeffrey',103,'stable',3,['english','presidential','place'],['Jeffrey','Jeff','Jed'],['Jeff','Jed']),
  n('Jeremiah','boy',['Hebrew'],'God will uplift',33,'rising',4,['biblical','strong','classic'],['Jeremy','Jerry','Jere'],['Jeremy','Jerry']),
  n('Jerome','boy',['Greek'],'sacred name',112,'stable',2,['greek','religious','classic'],['Jeremy','Jere','Hieronymus'],['Jerry']),
  n('Joel','boy',['Hebrew'],'God is willing',73,'stable',1,['biblical','classic','short'],['Joe','Joel','Jesse'],[]),
  n('John','boy',['Hebrew'],'God is gracious',7,'stable',1,['biblical','classic','royal'],['Jon','Johnny','Jack'],['Johnny','Jack']),
  n('Jonah','boy',['Hebrew'],'dove',43,'rising',2,['biblical','nature','vintage'],['Noah','Jonas','Jon'],[]),
  n('Jonathan','boy',['Hebrew'],'God has given',27,'stable',3,['biblical','classic','popular'],['Jon','Johnny','Jonathon'],['Jon','Johnny']),
  n('Jordan','boy',['Hebrew'],'to flow down',50,'stable',2,['biblical','neutral','popular'],['Jordin','Jordyn','Jory'],['Jordy']),
  n('Joseph','boy',['Hebrew'],'God will add',11,'stable',3,['biblical','classic','popular'],['Joe','Joey','Josef'],['Joe','Joey']),
  n('Josh','boy',['Hebrew'],'God is salvation',55,'stable',1,['hebrew','short','popular'],['Joshua','Josiah','Jesse'],[]),
  n('Joshua','boy',['Hebrew'],'God is salvation',14,'stable',3,['biblical','classic','popular'],['Josh','Josiah','Jesse'],['Josh']),
  n('Josiah','boy',['Hebrew'],'God supports, heals',36,'rising',3,['biblical','vintage','strong'],['Joshua','Joseph','Josias'],['Jo']),
  n('Julian','boy',['Latin'],'youthful',37,'rising',3,['latin','elegant','classic'],['Julius','Julien','Julio'],[]),
  n('Kai','boy',['Hawaiian','Welsh'],'sea, keeper of keys',40,'rising',1,['hawaiian','welsh','modern'],['Kade','Cai','Ky'],[]),
  n('Keir','boy',['Scottish','Irish'],'dark one',115,'rising',1,['scottish','dark','short'],['Kieran','Kier','Ciar'],[]),
  n('Kieran','boy',['Irish'],'little dark one',63,'stable',3,['irish','gaelic','dark'],['Ciaran','Keir','Kiran'],[]),
  n('Kyle','boy',['Scottish'],'narrow strait',66,'stable',1,['scottish','modern','short'],['Lyle','Kyler','Kile'],[]),
  n('Lance','boy',['Germanic'],'land',99,'stable',1,['germanic','classic','knight'],['Lancelot','Lance','Landon'],['Lan']),
  n('Landon','boy',['English'],'long hill',53,'stable',2,['english','modern','place'],['London','Landan','Brandon'],['Lan']),
  n('Lawrence','boy',['Latin'],'from Laurentum',88,'stable',2,['latin','classic','royal'],['Lars','Laurent','Laurence'],['Larry','Laurie']),
  n('Leo','boy',['Latin'],'lion',15,'rising',2,['latin','short','popular'],['Leon','Leonard','Leonidas'],[]),
  n('Leon','boy',['Greek','Latin'],'lion',59,'rising',2,['greek','strong','vintage'],['Leo','Leonard','Leone'],[]),
  n('Leonard','boy',['Germanic'],'lion-brave',92,'rising',3,['germanic','vintage','strong'],['Leo','Leon','Lenny'],['Leo','Lenny']),
  n('Lewis','boy',['Germanic'],'famous warrior',62,'stable',2,['germanic','royal','classic'],['Louis','Luis','Louie'],['Lew']),
  n('Liam','boy',['Irish','Germanic'],'strong-willed warrior',1,'stable',1,['popular','irish','strong'],['William','Liam','Leo'],[]),
  n('Lincoln','boy',['English'],'lake colony',51,'rising',2,['english','presidential','place'],['Link','Lincon','Lancelot'],['Link']),
  n('Logan','boy',['Scottish'],'little hollow',20,'stable',2,['scottish','popular','modern'],['Rogan','Logen','Hogan'],[]),
  n('Louis','boy',['French','Germanic'],'famous warrior',34,'rising',2,['french','royal','classic'],['Lewis','Luigi','Luis'],['Lou','Louie']),
  n('Luca','boy',['Italian','Latin'],'light',32,'rising',2,['italian','popular','modern'],['Lucas','Luke','Luca'],[]),
  n('Luke','boy',['Greek'],'light, illumination',18,'stable',1,['biblical','short','classic'],['Lucas','Luka','Lucius'],[]),
  n('Malachi','boy',['Hebrew'],'my messenger',69,'rising',3,['biblical','strong','vintage'],['Malakai','Malachai','Elijah'],['Kai','Mal']),
  n('Malcolm','boy',['Scottish'],'devotee of Saint Columba',89,'stable',2,['scottish','royal','classic'],['Malcom','Mac','Calum'],['Mal','Mac']),
  n('Marcus','boy',['Latin'],'of Mars, warlike',43,'stable',2,['roman','classic','strong'],['Mark','Marco','Marc'],[]),
  n('Mark','boy',['Latin'],'of Mars, warlike',48,'stable',1,['biblical','classic','popular'],['Marcus','Marc','Marco'],[]),
  n('Marley','boy',['English'],'pleasant wood',106,'rising',2,['english','nature','musical'],['Harley','Charlie','Harlow'],[]),
  n('Marshall','boy',['Germanic'],'horse servant',94,'stable',2,['germanic','occupational','vintage'],['Mars','Marsh','Marsden'],['Mars']),
  n('Martin','boy',['Latin'],'of Mars, warlike',76,'stable',2,['latin','classic','popular'],['Martino','Martijn','Marx'],['Marty']),
  n('Mason','boy',['English','French'],'stone worker',11,'stable',2,['english','occupational','modern'],['Jason','Maverick','Maxwell'],[]),
  n('Matthew','boy',['Hebrew'],'gift of God',16,'stable',3,['biblical','classic','popular'],['Matt','Matteo','Matthias'],['Matt','Matty']),
  n('Matteo','boy',['Italian','Hebrew'],'gift of God',42,'rising',3,['italian','modern','classic'],['Matthew','Mateo','Matthias'],['Matt']),
  n('Max','boy',['Latin'],'greatest',24,'stable',1,['latin','short','popular'],['Maximus','Maxwell','Maxfield'],[]),
  n('Maximus','boy',['Latin'],'greatest',66,'rising',3,['latin','strong','roman'],['Max','Maxfield','Magnus'],['Max']),
  n('Maxwell','boy',['Scottish'],'great spring',67,'stable',2,['scottish','classic','strong'],['Max','Maxell','Mac'],['Max','Mac']),
  n('Michael','boy',['Hebrew'],'who is like God',6,'stable',3,['biblical','classic','popular'],['Mike','Mick','Mikey'],['Mike','Mikey','Mick']),
  n('Miles','boy',['Germanic'],'soldier, merciful',41,'rising',1,['germanic','literary','vintage'],['Milo','Mile','Miles'],[]),
  n('Milo','boy',['Germanic'],'merciful',53,'rising',2,['germanic','vintage','sweet'],['Miles','Milos','Milous'],[]),
  n('Mohamed','boy',['Arabic'],'praised, commendable',45,'stable',3,['arabic','religious','popular'],['Muhammad','Mohammed','Ahmad'],['Mo']),
  n('Monty','boy',['Germanic','French'],'mountain hunter',100,'rising',2,['french','vintage','noble'],['Montgomery','Monte','Monty'],['Mont']),
  n('Morgan','boy',['Welsh'],'sea-born',81,'stable',2,['welsh','neutral','modern'],['Morrigan','Moro','Gordon'],[]),
  n('Morris','boy',['Latin'],'dark-skinned, Moorish',120,'stable',2,['latin','vintage','classic'],['Maurice','Morse','Morrison'],[]),
  n('Muhammad','boy',['Arabic'],'praised, commendable',40,'stable',3,['arabic','religious','popular'],['Mohamed','Mohammed','Ahmad'],['Mo']),
  n('Nathan','boy',['Hebrew'],'he gave',29,'stable',2,['biblical','popular','classic'],['Nathaniel','Nat','Nate'],['Nate']),
  n('Nathaniel','boy',['Hebrew'],'gift of God',55,'stable',4,['biblical','classic','elegant'],['Nathan','Nat','Nate'],['Nate','Nat']),
  n('Neil','boy',['Irish'],'champion',100,'stable',1,['irish','classic','short'],['Niall','Neal','Neill'],[]),
  n('Niall','boy',['Irish'],'champion',94,'rising',2,['irish','gaelic','classic'],['Neil','Neal','Nial'],[]),
  n('Nicholas','boy',['Greek'],'victorious people',22,'stable',3,['greek','classic','saint'],['Nick','Nicky','Nicolas'],['Nick','Nicky']),
  n('Nico','boy',['Greek','Italian'],'victorious',62,'rising',2,['greek','italian','modern'],['Nicolas','Nicholas','Nike'],[]),
  n('Noel','boy',['French'],'Christmas',99,'stable',2,['french','christmas','classic'],['Joel','Noel','Nowell'],[]),
  n('Nolan','boy',['Irish'],'champion',59,'rising',2,['irish','modern','popular'],['Nolen','Nolin','Dolan'],[]),
  n('Oakley','boy',['English'],'oak meadow',90,'rising',3,['english','nature','modern'],['Oak','Oak','Oakes'],[]),
  n('Oliver','boy',['Latin','French'],'olive tree',3,'rising',3,['classic','popular','nature'],['Olive','Owen','Oscar'],['Ollie']),
  n('Ollie','boy',['Latin'],'olive tree',61,'rising',3,['british','sweet','modern'],['Oliver','Olive','Roland'],[]),
  n('Omar','boy',['Arabic'],'flourishing, long-lived',77,'rising',2,['arabic','popular','classic'],['Umar','Amr','Omer'],[]),
  n('Oscar','boy',['Norse','Irish'],'divine spear',38,'rising',2,['norse','irish','vintage'],['Oskar','Oz','Ozzy'],['Oz','Ozzy']),
  n('Owen','boy',['Welsh','Latin'],'young warrior',29,'stable',2,['welsh','popular','classic'],['Owain','Ewan','Ewen'],[]),
  n('Parker','boy',['English'],'keeper of the park',46,'stable',2,['english','occupational','modern'],['Pierce','Paxton','Porter'],[]),
  n('Patrick','boy',['Latin'],'nobleman',54,'stable',2,['latin','irish','saint'],['Pat','Paddy','Patrice'],['Pat','Paddy']),
  n('Paul','boy',['Latin'],'small',62,'stable',1,['biblical','classic','popular'],['Pablo','Paolo','Pavlos'],[]),
  n('Paxton','boy',['English'],'peaceful settlement',80,'rising',2,['english','place','modern'],['Pax','Paxton','Paxten'],['Pax']),
  n('Peter','boy',['Greek'],'rock',25,'stable',2,['biblical','classic','royal'],['Pete','Piers','Pierre'],['Pete']),
  n('Philip','boy',['Greek'],'friend of horses',64,'stable',2,['greek','classic','royal'],['Phillip','Phil','Filip'],['Phil']),
  n('Pierce','boy',['English'],'rock',85,'rising',1,['english','noble','strong'],['Piers','Pierce','Percy'],[]),
  n('Preston','boy',['English'],'priest\'s settlement',79,'stable',2,['english','place','strong'],['Preson','Weston','Preston'],[]),
  n('Quentin','boy',['Latin'],'fifth',101,'rising',2,['latin','vintage','literary'],['Quinn','Quincy','Quentyn'],['Quinn']),
  n('Quinn','boy',['Irish'],'descendant of Conn',72,'stable',1,['irish','neutral','modern'],['Quin','Quentin','Quinn'],[]),
  n('Rafferty','boy',['Irish'],'abundance riches',120,'rising',3,['irish','vintage','spirited'],['Rafe','Rafferty','Raffy'],['Rafe','Raffy']),
  n('Ralph','boy',['Norse'],'wolf counsel',108,'rising',1,['norse','vintage','royal'],['Ralf','Rafe','Rolph'],[]),
  n('Reuben','boy',['Hebrew'],'behold, a son',86,'rising',2,['biblical','vintage','strong'],['Ruben','Rube','Rupert'],['Rube']),
  n('Rex','boy',['Latin'],'king',103,'rising',1,['latin','royal','vintage'],['Rexford','Rex','Rexx'],[]),
  n('Rhys','boy',['Welsh'],'ardour, enthusiasm',72,'rising',1,['welsh','short','classic'],['Reece','Rees','Rhys'],[]),
  n('Richard','boy',['Germanic'],'powerful ruler',35,'stable',3,['germanic','royal','classic'],['Rick','Rich','Richie'],['Rich','Rick','Richie']),
  n('Robert','boy',['Germanic'],'bright fame',20,'stable',2,['germanic','royal','classic'],['Rob','Bobby','Robin'],['Rob','Bobby','Bob']),
  n('Robin','boy',['Germanic'],'bright fame',89,'rising',2,['germanic','nature','vintage'],['Robert','Rob','Robinson'],[]),
  n('Ronan','boy',['Irish'],'little seal',72,'rising',2,['irish','gaelic','nature'],['Rowan','Roan','Ronan'],[]),
  n('Rory','boy',['Irish','Scottish'],'red king',64,'rising',2,['irish','scottish','spirited'],['Ruari','Ruaraidh','Roary'],[]),
  n('Ross','boy',['Scottish'],'headland, cape',95,'stable',1,['scottish','short','nature'],['Roscoe','Ross','Russel'],[]),
  n('Rowan','boy',['Irish'],'red-haired, rowan tree',55,'rising',2,['irish','nature','neutral'],['Ronan','Roan','Rowan'],[]),
  n('Roy','boy',['Celtic','French'],'king',107,'stable',1,['celtic','vintage','short'],['Raymond','Roy','Leroy'],[]),
  n('Rupert','boy',['Germanic'],'bright fame',88,'rising',2,['germanic','vintage','royal'],['Robert','Robin','Rupe'],['Rupe']),
  n('Ryan','boy',['Irish'],'little king',25,'stable',2,['irish','popular','modern'],['Bryan','Brian','Ryne'],[]),
  n('Samuel','boy',['Hebrew'],'God has heard',13,'stable',3,['biblical','classic','popular'],['Sam','Sammy','Saul'],['Sam','Sammy']),
  n('Scott','boy',['English','Scottish'],'from Scotland',76,'stable',1,['english','place','classic'],['Scot','Scottie','Scotty'],['Scottie']),
  n('Sean','boy',['Irish'],'God is gracious',57,'stable',1,['irish','gaelic','popular'],['Shawn','Shane','Shaun'],[]),
  n('Sebastian','boy',['Greek','Latin'],'venerable, revered',19,'rising',3,['greek','elegant','classic'],['Seb','Bastian','Basti'],['Seb']),
  n('Seth','boy',['Hebrew'],'appointed, placed',68,'stable',1,['biblical','short','classic'],['Sev','Sett','Heath'],[]),
  n('Shane','boy',['Irish'],'God is gracious',79,'stable',1,['irish','gaelic','modern'],['Sean','Shain','Wayne'],[]),
  n('Shawn','boy',['Irish'],'God is gracious',71,'stable',1,['irish','american','modern'],['Sean','Shane','Juan'],[]),
  n('Silas','boy',['Latin'],'wood, forest',46,'rising',2,['biblical','vintage','nature'],['Silo','Sylas','Eli'],[]),
  n('Simon','boy',['Hebrew'],'to hear, to be heard',55,'stable',2,['biblical','classic','popular'],['Simeon','Syme','Sy'],['Si']),
  n('Spencer','boy',['English'],'house steward',74,'stable',2,['english','occupational','modern'],['Spence','Spencer','Spenser'],['Spence']),
  n('Stanley','boy',['English'],'stone clearing',98,'rising',3,['english','vintage','strong'],['Stan','Standley','Stanly'],['Stan']),
  n('Stefan','boy',['Greek'],'crown',89,'rising',2,['greek','scandinavian','classic'],['Stephen','Steven','Stephan'],[]),
  n('Stephen','boy',['Greek'],'crown, garland',47,'stable',2,['greek','biblical','classic'],['Steven','Steve','Stefan'],['Steve']),
  n('Sterling','boy',['English'],'little star, genuine',95,'rising',2,['english','noble','modern'],['Sterling','Stirling','Starling'],[]),
  n('Sullivan','boy',['Irish'],'dark-eyed',101,'rising',3,['irish','gaelic','vintage'],['Sully','Sullivann','Sylvan'],['Sully']),
  n('Theodore','boy',['Greek'],'gift of God',20,'rising',3,['greek','vintage','royal'],['Theo','Ted','Teddy'],['Theo','Ted','Teddy']),
  n('Theo','boy',['Greek'],'gift of God',30,'rising',2,['greek','popular','modern'],['Theodore','Theobald','Thad'],['Ted']),
  n('Thomas','boy',['Aramaic'],'twin',12,'stable',2,['biblical','royal','classic'],['Tom','Tommy','Tomas'],['Tom','Tommy']),
  n('Timothy','boy',['Greek'],'honouring God',58,'stable',3,['biblical','classic','popular'],['Tim','Timmy','Timo'],['Tim','Timmy']),
  n('Tobias','boy',['Hebrew'],'God is good',66,'rising',3,['biblical','vintage','elegant'],['Toby','Tobi','Tobia'],['Toby']),
  n('Toby','boy',['Hebrew'],'God is good',74,'rising',2,['biblical','sweet','vintage'],['Tobias','Tobi','Coby'],[]),
  n('Tom','boy',['Aramaic'],'twin',56,'stable',1,['classic','short','popular'],['Thomas','Tommy','Tim'],['Tommy']),
  n('Travis','boy',['French'],'to cross',84,'stable',2,['french','modern','strong'],['Trevis','Travis','Trevin'],[]),
  n('Trevor','boy',['Welsh'],'large settlement',80,'stable',2,['welsh','classic','modern'],['Trevar','Trever','Trevor'],[]),
  n('Tristan','boy',['Celtic'],'noise, tumult',62,'rising',2,['celtic','arthurian','romantic'],['Tristian','Tristam','Tristen'],[]),
  n('Tyler','boy',['English'],'tile maker',36,'stable',2,['english','occupational','modern'],['Taylor','Kyler','Tiler'],[]),
  n('Ulysses','boy',['Latin','Greek'],'wrathful, wounded',130,'rising',3,['latin','literary','mythological'],['Uliss','Odysseus','Jules'],[]),
  n('Victor','boy',['Latin'],'conqueror, winner',80,'rising',2,['latin','roman','strong'],['Vick','Vittorio','Viktor'],['Vic']),
  n('Vincent','boy',['Latin'],'to conquer',69,'rising',2,['latin','artistic','classic'],['Vince','Vincenzo','Vinnie'],['Vince','Vinnie']),
  n('Wade','boy',['English'],'to go, ford',105,'stable',1,['english','nature','vintage'],['Cade','Blake','Slade'],[]),
  n('Walter','boy',['Germanic'],'ruler of the army',88,'rising',2,['germanic','vintage','royal'],['Walt','Wally','Walder'],['Walt','Wally']),
  n('Wesley','boy',['English'],'western meadow',65,'stable',3,['english','classic','place'],['Westley','Wes','Weston'],['Wes']),
  n('Wilder','boy',['English'],'one who lives near woods',79,'rising',2,['english','nature','modern'],['Wild','Wilde','Wilder'],[]),
  n('William','boy',['Germanic'],'resolute protector',6,'stable',3,['germanic','royal','classic'],['Will','Liam','Wilson'],['Will','Bill','Wills']),
  n('Wyatt','boy',['English'],'brave in war',34,'rising',2,['english','western','modern'],['Wiatt','Wyat','Rhett'],[]),
  n('Xavier','boy',['Arabic','Basque'],'new house, bright',45,'rising',3,['arabic','modern','strong'],['Xander','Xavi','Javier'],['X','Xavi']),
  n('Zach','boy',['Hebrew'],'God has remembered',73,'stable',1,['hebrew','short','popular'],['Zachary','Zack','Zac'],['Zac']),
  n('Zachary','boy',['Hebrew'],'God has remembered',38,'stable',3,['biblical','classic','popular'],['Zach','Zac','Zachariah'],['Zach','Zac']),
  n('Zane','boy',['Hebrew'],'God is gracious',58,'rising',1,['hebrew','modern','short'],['Zayne','Xane','Lane'],[]),

  // ── NEUTRAL ──────────────────────────────────────────────────────────────────
  n('Alex','neutral',['Greek'],'defender of the people',20,'stable',2,['popular','neutral','short'],['Alexandra','Alexander','Alexis'],[]),
  n('Alexis','neutral',['Greek'],'defending warrior',35,'stable',3,['greek','neutral','modern'],['Alex','Alexa','Alexander'],[]),
  n('Angel','neutral',['Greek'],'messenger of God',40,'stable',2,['religious','neutral','modern'],['Angela','Angelo','Angie'],[]),
  n('Ari','neutral',['Hebrew','Greek'],'lion, superior',65,'rising',2,['hebrew','greek','short'],['Aria','Ariel','Ariana'],[]),
  n('Ash','neutral',['English'],'ash tree',60,'rising',1,['nature','short','modern'],['Asher','Ashley','Ashton'],[]),
  n('Bailey','neutral',['English'],'bailiff, city fortification',50,'stable',3,['english','neutral','modern'],['Bailee','Kylie','Hailey'],[]),
  n('Bay','neutral',['English'],'berry, sea inlet',95,'rising',1,['nature','short','modern'],['Baye','Bay','Bay'],[]),
  n('Billie','neutral',['Germanic'],'will helmet',48,'rising',3,['germanic','vintage','neutral'],['Billy','William','Willa'],[]),
  n('Bo','neutral',['Norse'],'to live, farmer',78,'rising',1,['norse','short','simple'],['Bobby','Beau','Joe'],[]),
  n('Cameron','neutral',['Scottish'],'crooked nose',45,'stable',3,['scottish','neutral','popular'],['Camron','Cam','Camden'],['Cam']),
  n('Casey','neutral',['Irish'],'vigilant, watchful',56,'stable',3,['irish','neutral','modern'],['Case','Kasey','Cassie'],[]),
  n('Charlie','neutral',['Germanic'],'free man',25,'rising',3,['germanic','neutral','popular'],['Charles','Charlotte','Charley'],[]),
  n('Dakota','neutral',['Native American'],'friendly one',55,'stable',3,['native american','place','neutral'],['Dakotah','Denver','Nevada'],[]),
  n('Dallas','neutral',['Scottish'],'from the meadow',66,'stable',2,['scottish','place','neutral'],['Dallis','Denver','Dallas'],[]),
  n('Devon','neutral',['English','Celtic'],'defender',73,'stable',2,['english','place','neutral'],['Devin','Deven','Devon'],[]),
  n('Drew','neutral',['Greek'],'strong, manly',62,'stable',1,['greek','short','modern'],['Andrew','Andrea','Dru'],[]),
  n('Dylan','neutral',['Welsh'],'sea, great tide',30,'stable',2,['welsh','neutral','popular'],['Dillon','Dillan','Dylen'],[]),
  n('Eden','neutral',['Hebrew'],'paradise, pleasure',45,'rising',2,['biblical','nature','modern'],['Edan','Aiden','Jayden'],[]),
  n('Elliot','neutral',['English','Hebrew'],'the Lord is my God',40,'rising',3,['english','literary','neutral'],['Elliott','Eliot','Elias'],['Eli']),
  n('Ellis','neutral',['Welsh'],'benevolent',73,'rising',2,['welsh','vintage','neutral'],['Ellie','Eli','Ellery'],[]),
  n('Emery','neutral',['Germanic'],'work power',63,'rising',3,['germanic','neutral','modern'],['Emory','Avery','Emerson'],[]),
  n('Emerson','neutral',['Germanic'],'son of Emery',57,'rising',3,['germanic','neutral','modern'],['Emery','Emery','Em'],['Em']),
  n('Evan','neutral',['Welsh'],'God is gracious',42,'stable',2,['welsh','neutral','popular'],['Ewan','Ivan','Ian'],[]),
  n('Finley','neutral',['Irish','Scottish'],'fair warrior',44,'rising',3,['irish','neutral','modern'],['Finn','Findlay','Finlay'],['Finn']),
  n('Frankie','neutral',['Germanic'],'free man',60,'rising',3,['germanic','neutral','sweet'],['Frank','Frances','Francis'],[]),
  n('Harley','neutral',['English'],'hare meadow',75,'stable',2,['english','nature','neutral'],['Harlow','Harvey','Harper'],[]),
  n('Harper','neutral',['English'],'harp player',10,'rising',2,['english','musical','neutral'],['Harlow','Haven','Hailey'],[]),
  n('Hayden','neutral',['English'],'heathen, fire',52,'stable',2,['english','neutral','modern'],['Haden','Aiden','Caden'],[]),
  n('Jamie','neutral',['Hebrew'],'supplanter',48,'stable',3,['hebrew','neutral','popular'],['James','Jami','Jay'],[]),
  n('Jess','neutral',['Hebrew'],'God beholds',66,'stable',1,['hebrew','short','neutral'],['Jesse','Jessica','Jessie'],[]),
  n('Jesse','neutral',['Hebrew'],'God exists',53,'stable',2,['biblical','neutral','classic'],['Jessica','Jess','Jessie'],[]),
  n('Jordan','neutral',['Hebrew'],'to flow down, descend',44,'stable',2,['biblical','neutral','popular'],['Jordin','Jordyn','Jory'],['Jordy']),
  n('Jules','neutral',['Latin'],'youthful',73,'rising',1,['latin','neutral','chic'],['Julia','Julian','Julie'],[]),
  n('Juniper','neutral',['Latin'],'juniper tree',68,'rising',3,['latin','nature','modern'],['June','Juno','Juni'],['Juni']),
  n('Juno','neutral',['Latin'],'Roman goddess',78,'rising',2,['roman','mythological','modern'],['June','Juniper','Luna'],[]),
  n('Justice','neutral',['Latin'],'justice, righteous',75,'stable',2,['virtue','neutral','modern'],['Justus','Just','Justine'],[]),
  n('Karter','neutral',['English'],'transporter of goods',82,'rising',2,['english','neutral','modern'],['Carter','Kade','Karson'],[]),
  n('Kendall','neutral',['English'],'valley of the River Kent',66,'stable',2,['english','neutral','modern'],['Kendal','Kendra','Kenley'],[]),
  n('Kennedy','neutral',['Irish'],'helmeted chief',58,'rising',3,['irish','neutral','modern'],['Kenley','Kenna','Kent'],[]),
  n('Kerry','neutral',['Irish'],'dark-haired, dark eyes',90,'stable',2,['irish','neutral','classic'],['Carrie','Keri','Kerry'],[]),
  n('Lane','neutral',['English'],'path, roadway',69,'rising',1,['english','nature','neutral'],['Laine','Layne','Lana'],[]),
  n('Lee','neutral',['English'],'meadow, clearing',80,'stable',1,['english','short','neutral'],['Leigh','Lea','Ley'],[]),
  n('Lennox','neutral',['Scottish'],'elm grove',64,'rising',2,['scottish','nature','modern'],['Lenox','Lenny','Lennon'],['Len','Lenny']),
  n('Linden','neutral',['English'],'linden tree hill',86,'rising',2,['english','nature','neutral'],['Lyndon','Lindon','Linden'],[]),
  n('London','neutral',['English'],'great river',73,'rising',2,['english','place','neutral'],['Landon','Brooklyn','Brittany'],[]),
  n('Luca','neutral',['Italian','Latin'],'light',35,'rising',2,['italian','neutral','modern'],['Luke','Lucas','Lucia'],[]),
  n('Lynn','neutral',['Welsh','English'],'lake, waterfall',90,'stable',1,['welsh','nature','classic'],['Lynne','Lin','Lindy'],[]),
  n('Marlowe','neutral',['English'],'driftwood',80,'rising',2,['english','literary','neutral'],['Marlo','Marlow','Harlow'],[]),
  n('Morgan','neutral',['Welsh'],'sea-born',44,'stable',2,['welsh','neutral','popular'],['Morrigan','Morgana','Morgen'],[]),
  n('Nico','neutral',['Greek','Italian'],'victorious',55,'rising',2,['greek','italian','neutral'],['Nicolas','Nicole','Nike'],[]),
  n('Oakley','neutral',['English'],'oak meadow',83,'rising',3,['english','nature','neutral'],['Oak','Oaklee','Oxley'],[]),
  n('Parker','neutral',['English'],'park keeper',38,'stable',2,['english','occupational','neutral'],['Pace','Pierce','Porter'],[]),
  n('Payton','neutral',['English'],'fighting-man\'s estate',60,'stable',2,['english','neutral','popular'],['Peyton','Paton','Paisley'],[]),
  n('Peyton','neutral',['English'],'fighting-man\'s estate',42,'stable',2,['english','neutral','popular'],['Payton','Payne','Preston'],[]),
  n('Phoenix','neutral',['Greek'],'dark red, mythical bird',43,'rising',2,['greek','mythological','modern'],['Phelan','Finley','Felix'],[]),
  n('Quinn','neutral',['Irish'],'descendant of Conn',38,'rising',1,['irish','neutral','modern'],['Quin','Quincy','Quinn'],[]),
  n('Reagan','neutral',['Irish'],'little king',63,'rising',3,['irish','neutral','modern'],['Regan','Raegan','Logan'],[]),
  n('Reese','neutral',['Welsh'],'ardour, enthusiasm',56,'rising',1,['welsh','neutral','modern'],['Reece','Rees','Rhys'],[]),
  n('Remi','neutral',['French'],'oarsman',67,'rising',3,['french','neutral','modern'],['Remy','Remi','Emil'],[]),
  n('Remy','neutral',['French'],'oarsman',62,'rising',2,['french','neutral','chic'],['Remi','Remi','Emil'],[]),
  n('Riley','neutral',['Irish','English'],'courageous',15,'stable',2,['irish','neutral','popular'],['Ryan','Rylee','Rilee'],[]),
  n('Robin','neutral',['Germanic'],'bright fame',72,'stable',2,['germanic','nature','neutral'],['Robert','Robyn','Rob'],[]),
  n('Rowan','neutral',['Irish'],'rowan tree',48,'rising',2,['irish','nature','neutral'],['Ronan','Roan','Row'],[]),
  n('Ryan','neutral',['Irish'],'little king',22,'stable',2,['irish','neutral','popular'],['Bryan','Brian','Ryne'],[]),
  n('Rylee','neutral',['Irish'],'courageous',62,'stable',3,['irish','neutral','modern'],['Riley','Rylie','Rilee'],[]),
  n('Sage','neutral',['English'],'wise, herb',60,'rising',1,['nature','virtue','neutral'],['Sage','Paige','Page'],[]),
  n('Sam','neutral',['Hebrew'],'God has heard',35,'stable',1,['biblical','short','neutral'],['Samuel','Samantha','Sammy'],[]),
  n('Scout','neutral',['French'],'to listen',80,'rising',1,['french','nature','modern'],['Skye','River','Scout'],[]),
  n('Shiloh','neutral',['Hebrew'],'tranquil, peaceful',65,'rising',2,['biblical','nature','neutral'],['Shilo','Shiloe','Silas'],[]),
  n('Sidney','neutral',['French','English'],'wide island',75,'stable',3,['french','place','neutral'],['Sydney','Sid','Sydney'],['Sid']),
  n('Skyler','neutral',['Dutch'],'scholar',48,'rising',3,['dutch','neutral','modern'],['Skye','Skylar','Taylor'],[]),
  n('Stevie','neutral',['Greek'],'crown',58,'rising',3,['greek','musical','neutral'],['Steve','Stephanie','Steven'],[]),
  n('Sydney','neutral',['French','English'],'wide island',56,'stable',2,['french','place','neutral'],['Sidney','Sid','Cydney'],['Sid']),
  n('Taylor','neutral',['English'],'tailor',34,'stable',2,['english','occupational','neutral'],['Tyler','Tatum','Tayler'],[]),
  n('Tatum','neutral',['English'],'Tate\'s homestead',67,'rising',2,['english','neutral','modern'],['Tatumn','Tate','Taylor'],[]),
  n('Tristan','neutral',['Celtic'],'noise, tumult',58,'rising',2,['celtic','neutral','romantic'],['Tristian','Tristam','Tristen'],[]),
  n('Tyler','neutral',['English'],'tile maker',40,'stable',2,['english','occupational','neutral'],['Taylor','Kyler','Tiler'],[]),
  n('Wren','neutral',['English'],'tiny bird',61,'rising',1,['nature','bird','neutral'],['Ren','Robin','Wren'],[]),
];

const all = [...existing, ...newNames];
writeFileSync('src/data/baby-names.json', JSON.stringify(all, null, 2), 'utf8');
console.log(`✅ Done! Total names: ${all.length} (added ${newNames.length})`);
